var startingCardInfo = [
    {
        "Name": "Take an Opportunity set",
        "Type": "Starting",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2/8"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "1/2"},
            {"ID": "Opportunity set"}
        ],
        "Text": "Do either of the following:\r - Pay 2 Influence. Take an Opportunity set.\r - Pay 8 Influence. Take 2 Opportunity sets.",
        "End": "Return",
        "Benefit icon": [{"ID": "Opportunity set"}],
    },
    {
        "Name": "Common projects",
        "Type": "Starting",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1/4/9"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-X"},
            {"ID": "Resource"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "1/2/3"},
            {"ID": "Place tile", "Text": "X", "Optional": ["Multi"]}
        ],
        "Text": "Do any one of the following:\r - Pay 1 Influence. Build a Common project.\r - Pay 4 Influence. Build 2 Common projects.\r - Pay 9 Influence. Build 3 Common projects.",
        "End": "Return",
        "Benefit icon": [{"ID": "Place tile", "Optional": ["Multi"]}],
    },
    {
        "Name": "Buy resources",
        "Type": "Starting",
        "Order": "Player",
        "Icons": [
            {"ID": "Market up"},
            {"ID": "Pay amount", "Text": "-X"},
            {"ID": "Aureus"},
            {"ID": "Multi arrow"},
            {"ID": "Gain amount", "Text": "+5"},
            {"ID": "Resource"},
        ],
        "Text": "Increase the price of a resource in the Market by 1. Pay the new price in Aureus and gain 5 of that resource.\rRepeat as many times as you want for the same resource.",
        "End": "Return",
        "Benefit icon": [{"ID": "Resource"}],
    },
    {
        "Name": "Sell resources",
        "Type": "Starting",
        "Order": "Player",
        "Icons": [
            {"ID": "Market down"},
            {"ID": "Pay amount", "Text": "-5"},
            {"ID": "Resource"},
            {"ID": "Multi arrow"},
            {"ID": "Gain amount", "Text": "+X"},
            {"ID": "Aureus"},
        ],
        "Text": "Decrease the price of a resource in the Market by 1. Pay 5 of that resource and gain the new price in Aureus.\rRepeat as many times as you want for the same resource.",
        "End": "Return",
        "Benefit icon": [{"ID": "Aureus"}],
    },
];

var opportunityCardInfo = [
    //////////////////
    // 5% resources //
    //////////////////
    {
        "Name": "Feast",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+3"},
            {"ID": "Grain"},
        ],
        "Text": "Pay 1 Influence. Gain 3 Grain.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Grain"}],
    },
    {
        "Name": "Lumber cache",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+3"},
            {"ID": "Wood"},
        ],
        "Text": "Pay 1 Influence. Gain 3 Wood.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Wood"}],
    },
    {
        "Name": "Mineral discovery",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+3"},
            {"ID": "Metal"},
        ],
        "Text": "Pay 1 Influence. Gain 3 Metal.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Metal"}],
    },
    {
        "Name": "Write a Grand Odyssey",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+3"},
            {"ID": "Papyrus"},
        ],
        "Text": "Pay 1 Influence. Gain 3 Papyrus.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Papyrus"}],
    },
    {
        "Name": "Plenty",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+5"},
            {"ID": "Grain"},
        ],
        "Text": "Pay 1 Influence. Gain 5 Grain.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Grain"}],
    },
    ////////////////////////////
    // 20% resources + pillar //
    ////////////////////////////
    // 4% grain + pillar
    {
        "Name": "Water wheel",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-4"},
            {"ID": "Wood"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+4"},
            {"ID": "Grain"},
        ],
        "Text": "Pay 1 Influence and 4 Wood. Gain 4 Grain.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Place tile", "Optional": ["Multi"]}],
        "Trigger text": "When the card above places a tile, gain 1 Grain.",
        "Benefit icon": [{"ID": "Grain"}],
    },
    {
        "Name": "Experimental crops",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Decrease production grain"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+3"},
            {"ID": "Grain"},
        ],
        "Text": "Reduce your Grain production by 1. Gain 3 Grain.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Production resource"}],
        "Trigger text": "When the card above increases your Grain, Wood, Metal, or Papyrus production, gain 1 Grain.",
        "Benefit icon": [{"ID": "Grain"}],
    },
    {
        "Name": "Deal with the baker",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Grain"},
        ],
        "Text": "Pay 2 Influence. Gain 1 Grain.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Aureus"}],
        "Trigger text": "When the card above gains Aureus, gain 1 Grain.",
        "Benefit icon": [{"ID": "Grain"}],
    },
    {
        "Name": "Join the farmer's guild",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Grain"},
        ],
        "Text": "Pay 2 Influence. Gain 2 Grain.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Opportunity set"}],
        "Trigger text": "When the card above takes an Opportunity set, gain 1 Grain.",
        "Benefit icon": [{"ID": "Grain"}],
    },
    // 4% wood + pillar
    {
        "Name": "Mule carts",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Wood"},
        ],
        "Text": "Pay 1 Influence. Gain 1 Wood.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Resource"}],
        "Trigger text": "When the card above gains Grain, Wood, Metal, or Papyrus, gain 1 Wood.",
        "Benefit icon": [{"ID": "Wood"}],
    },
    {
        "Name": "Construction techniques",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Wood"},
        ],
        "Text": "Pay 1 Influence. Gain 1 Wood.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Place tile", "Optional": ["Multi"]}],
        "Trigger text": "When the card above places a tile, gain 1 Wood.",
        "Benefit icon": [{"ID": "Wood"}],
    },
    {
        "Name": "Reused cellar barrels",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Decrease production wood"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+3"},
            {"ID": "Wood"},
        ],
        "Text": "Reduce your Wood production by 1. Gain 3 Wood.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Production resource"}],
        "Trigger text": "When the card above increases your Grain, Wood, Metal, or Papyrus production, gain 1 Wood.",
        "Benefit icon": [{"ID": "Wood"}],
    },
    {
        "Name": "Resource management",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Wood"},
        ],
        "Text": "Pay 2 Influence. Gain 2 Wood.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Aureus"}],
        "Trigger text": "When the card above gains Aureus, gain 1 Wood.",
        "Benefit icon": [{"ID": "Wood"}],
    },
    // 4% metal + pillar
    {
        "Name": "Wealthy relatives",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Aureus"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Metal"},
        ],
        "Text": "Pay 1 Influence and 2 Aureus. Gain 2 Metal.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Wealth"}],
        "Trigger text": "When the card above increases your Wealth, gain 1 Metal.",
        "Benefit icon": [{"ID": "Metal"}],
    },
    {
        "Name": "Merchant ship contract",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Metal"},
        ],
        "Text": "Pay 2 Influence. Gain 2 Metal.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Resource"}],
        "Trigger text": "When the card above gains Grain, Wood, Metal, or Papyrus, gain 1 Metal.",
        "Benefit icon": [{"ID": "Metal"}],
    },
    {
        "Name": "Jewelry expertise",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Metal"},
        ],
        "Text": "Pay 2 Influence. Gain 1 Metal.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Aureus"}],
        "Trigger text": "When the card above gains Aureus, gain 1 Metal.",
        "Benefit icon": [{"ID": "Metal"}],
    },
    {
        "Name": "Forged tools",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+3"},
            {"ID": "Metal"},
        ],
        "Text": "Pay 1 Influence. Gain 3 Metal.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Production resource"}],
        "Trigger text": "When the card above increases your Grain, Wood, Metal, or Papyrus production, gain 1 Metal.",
        "Benefit icon": [{"ID": "Metal"}],
    },
    // 4% papyrus + pillar
    {
        "Name": "Lecture at the University",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Papyrus"},
        ],
        "Text": "Pay 2 Influence. Gain 2 Papyrus.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Resource"}],
        "Trigger text": "When the card above gains Grain, Wood, Metal, or Papyrus, gain 1 Papyrus.",
        "Benefit icon": [{"ID": "Papyrus"}],
    },
    {
        "Name": "Foreign connections",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Papyrus"},
        ],
        "Text": "Pay 1 Influence. Gain 2 Papyrus.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Power"}],
        "Trigger text": "When the card above increases your Power, gain 1 Papyrus.",
        "Benefit icon": [{"ID": "Papyrus"}],
    },
    {
        "Name": "Friends in the Senate",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Papyrus"},
        ],
        "Text": "Pay 2 Influence. Gain 1 Papyrus.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Opportunity set"}],
        "Trigger text": "When the card above takes an Opportunity set, gain 1 Papyrus.",
        "Benefit icon": [{"ID": "Papyrus"}],
    },
    {
        "Name": "Patron of the library",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Papyrus"},
        ],
        "Text": "Pay 2 Influence. Gain 1 Papyrus.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Aureus"}],
        "Trigger text": "When the card above gains Aureus, gain 1 Papyrus.",
        "Benefit icon": [{"ID": "Papyrus"}],
    },
    // 4% aureus + pillar
    {
        "Name": "Double entry accounting",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Papyrus"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+3"},
            {"ID": "Aureus"},
        ],
        "Text": "Pay 1 Influence and 3 Papyrus. Gain 3 Aureus.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Resource"}],
        "Trigger text": "When the card above gains Grain, Wood, Metal, or Papyrus, gain 1 Aureus.",
        "Benefit icon": [{"ID": "Aureus"}],
    },
    {
        "Name": "Connection with the guilds",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Metal"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+3"},
            {"ID": "Aureus"},
        ],
        "Text": "Pay 1 Influence and 3 Metal. Gain 3 Aureus.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Resource"}],
        "Trigger text": "When the card above gains Grain, Wood, Metal, or Papyrus, gain 1 Aureus.",
        "Benefit icon": [{"ID": "Aureus"}],
    },
    {
        "Name": "Supplies for Rome",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Grain"},
            {"ID": "Arrow"          },
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Aureus"},
        ],
        "Text": "Pay 1 Influence and 3 Grain. Gain 1 Aureus.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Resource"}],
        "Trigger text": "When the card above gains Grain, Wood, Metal, or Papyrus, gain 1 Aureus.",
        "Benefit icon": [{"ID": "Aureus"}],
    },
    {
        "Name": "Presitigious architecture",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Papyrus"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+3"},
            {"ID": "Aureus"},
        ],
        "Text": "Pay 2 Influence and 2 Papyrus. Gain 3 Aureus.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Place tile", "Optional": ["Multi"]}],
        "Trigger text": "When the card above places a tile, gain 1 Aureus.",
        "Benefit icon": [{"ID": "Aureus"}],
    },
    ////////////////////
    // 10% production //
    ////////////////////
    // 2% production grain
    {
        "Name": "Farming techniques",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Production grain"},
        ],
        "Text": "Pay 2 Influence. Increase your Grain production by 1.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Production grain"}],
    },
    {
        "Name": "Rotating crops",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Grain"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Production grain"},
        ],
        "Text": "Pay 1 Influence and 1 Grain. Increase your Grain production by 1.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Production grain"}],
    },
    // 2% production wood
    {
        "Name": "Logging techniques",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Production wood"},
        ],
        "Text": "Pay 2 Influence. Increase your Wood production by 1.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Production wood"}],
    },
    {
        "Name": "Selective cutting",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Wood"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Production wood"},
        ],
        "Text": "Pay 1 Influence and 1 Wood. Increase your Wood production by 1.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Production wood"}],
    },
    // 2% production metal
    {
        "Name": "Mining techniques",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Production metal"},
        ],
        "Text": "Pay 2 Influence. Increase your Metal production by 1.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Production metal"}],
    },
    {
        "Name": "Mining equipment",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Metal"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Production metal"},
        ],
        "Text": "Pay 1 Influence and 1 Metal. Increase your Metal production by 1.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Production metal"}],
    },
    // 2% production papyrus
    {
        "Name": "Paperforming techniques",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Production papyrus"},
        ],
        "Text": "Pay 2 Influence. Increase your Papyrus production by 1.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Production papyrus"}],
    },
    {
        "Name": "Paperforming training",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Papyrus"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Production papyrus"},
        ],
        "Text": "Pay 1 Influence and 1 Papyrus. Increase your Papyrus production by 1.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Production papyrus"}],
    },
    // 2% city layout -> production resource of choice
    {
        "Name": "Connections",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile owned", "Text": "H", "Optional": ["Home"]},
            {"ID": "Tile adjacent", "Text": "C", "Optional": ["Civic"]},
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Production resource"},
        ],
        "Text": "You must own a Home adjacent to at least 1 Civic building.\rPay 2 Influence. Increase your Grain, Wood, Metal, or Papyrus production (your choice) by 1.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Production resource"}],
    },
    {
        "Name": "Business accument",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile owned", "Text": "S", "Optional": ["Shop"]},
            {"ID": "Tile adjacent", "Text": "C", "Optional": ["Civic"]},
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Production resource"},
        ],
        "Text": "You must own a Shop adjacent to at least 1 Civic building.\rPay 2 Influence. Increase your Grain, Wood, Metal, or Papyrus production (your choice) by 1.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Production resource"}],
    },
    ///////////////////////////////////////////
    // 5% city layout -> production + pillar //
    ///////////////////////////////////////////
    {
        "Name": "Central crop planning",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile owned", "Text": "H", "Optional": ["Home"]},
            {"ID": "Tile adjacent", "Text": "C", "Optional": ["Civic"]},
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Production grain"},
        ],
        "Text": "You must own a Home adjacent to at least 1 Civic building. Pay 2 Influence. Increase your Grain production by 1.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Power"}],
        "Trigger text": "When the card above increases your Power, increase your Grain production by 1.",
        "Benefit icon": [{"ID": "Production grain"}],
    },
    {
        "Name": "Selective breeding stock",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile owned", "Text": "S", "Optional": ["Shop"]},
            {"ID": "Tile adjacent", "Text": "H", "Optional": ["Home"]},
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Production grain"},
        ],
        "Text": "You must own a Shop adjacent to at least 1 Home. Pay 3 Influence. Increase your Grain production by 1.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Wealth"}],
        "Trigger text": "When the card above increases your Wealth, increase your Grain production by 1.",
        "Benefit icon": [{"ID": "Production grain"}],
    },
    {
        "Name": "Grand forested estate",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile before adjacent", "Text": "H", "Optional": ["Home"]},
            {"ID": "Tile owned", "Text": "H", "Optional": ["Home"]},
            {"ID": "Tile adjacent", "Text": "H", "Optional": ["Home"]},
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Production wood"},
        ],
        "Text": "You must own a Home adjacent to at least 2 other Homes. Pay 3 Influence. Increase your Wood production by 1.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Production resource"}],
        "Trigger text": "When the card above increases your Grain, Wood, Metal, or Papyrus production, increase your Wood production by 1.",
        "Benefit icon": [{"ID": "Production wood"}],
    },
    {
        "Name": "Metallurgy craftsmanship",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile owned", "Text": "T", "Optional": ["Temple"]},
            {"ID": "Tile adjacent", "Text": "T", "Optional": ["Temple"]},
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Production metal"},
        ],
        "Text": "You must own a Temple adjacent to at least 1 other Temple. Pay 3 Influence. Increase your Metal production by 1.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Production resource"}],
        "Trigger text": "When the card above increases your Grain, Wood, Metal, or Papyrus prodution, increase your Metal production by 1.",
        "Benefit icon": [{"ID": "Production metal"}],
    },
    {
        "Name": "Economies of scale",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile owned", "Text": "S", "Optional": ["Shop"]},
            {"ID": "Tile owned", "Text": "S", "Optional": ["Shop"]},
            {"ID": "Tile owned", "Text": "C", "Optional": ["Civic"]},
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Production papyrus"},
        ],
        "Text": "You must own at least 2 Shops and one Civic building. Pay 2 Influence. Increase your Papyrus production by 1.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Wealth"}],
        "Trigger text": "When the card above increases your Wealth, increase your Papyrus production by 1.",
        "Benefit icon": [{"ID": "Production papyrus"}],
    },
    ///////////////////////
    // 5% power / wealth //
    ///////////////////////
    {
        "Name": "Lead a cohort",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-6"},
            {"ID": "Metal"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Power"},
        ],
        "Text": "Pay 3 Influence and 6 Metal. Increase your Power by 1.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Power"}],
    },
    {
        "Name": "Political circles",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-8"},
            {"ID": "Aureus"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Power"},
        ],
        "Text": "Pay 3 Influence and 8 Aureus. Increase your Power by 1.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Power"}],
    },
    {
        "Name": "Political marriage",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-6"},
            {"ID": "Grain"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Wealth"},
        ],
        "Text": "Pay 3 Influence and 6 Grain. Increase your Wealth by 1.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Wealth"}],
    },
    {
        "Name": "Business partnerships",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-7"},
            {"ID": "Aureus"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Wealth"},
        ],
        "Text": "Pay 3 Influence and 7 Aureus. Increase your Wealth by 1.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Wealth"}],
    },
    {
        "Name": "Bonfire celebration",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-6"},
            {"ID": "Wood"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Wealth"},
        ],
        "Text": "Pay 2 Influence and 6 Wood. Increase your Wealth by 1.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Wealth"}],
    },
    ///////////////////////////////////////
    // 15% city layout -> power / wealth //
    ///////////////////////////////////////
    {
        "Name": "Improve literacy",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile before adjacent", "Text": "H", "Optional": ["Home"]},
            {"ID": "Tile owned", "Text": "C", "Optional": ["Civic"]},
            {"ID": "Tile adjacent", "Text": "H", "Optional": ["Home"]},
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Wealth"},
        ],
        "Text": "You must own a Civic building adjacent to at least 2 Homes.\rPay 1 Influence. Increase your Wealth by 2.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Wealth"}],
    },
    {
        "Name": "Magnate",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile before adjacent", "Text": "S", "Optional": ["Shop"]},
            {"ID": "Tile owned", "Text": "C", "Optional": ["Civic"]},
            {"ID": "Tile adjacent", "Text": "S", "Optional": ["Shop"]},
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Wealth"},
        ],
        "Text": "You must own a Civic building adjacent to at least 2 Shops.\rPay 1 Influence. Increase your Wealth by 2.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Wealth"}],
    },
    {
        "Name": "Pious",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile before adjacent", "Text": "T", "Optional": ["Temple"]},
            {"ID": "Tile owned", "Text": "C", "Optional": ["Civic"]},
            {"ID": "Tile adjacent", "Text": "T", "Optional": ["Temple"]},
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Power"},
        ],
        "Text": "You must own a Civic building adjacent to at least 2 Temples.\rPay 1 Influence. Increase your Power by 2.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Power"}],
    },
    {
        "Name": "Civic square",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile before adjacent", "Text": "C", "Optional": ["Civic"]},
            {"ID": "Tile owned", "Text": "C", "Optional": ["Civic"]},
            {"ID": "Tile adjacent", "Text": "C", "Optional": ["Civic"]},
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Wealth"},
        ],
        "Text": "You must own a Civic building adjacent to at least 2 other Civic buildings.\rPay 1 Influence. Increase your Wealth by 2.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Wealth"}],
    },
    {
        "Name": "Record history",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile before adjacent", "Text": "M", "Optional": ["Military"]},
            {"ID": "Tile owned", "Text": "C", "Optional": ["Civic"]},
            {"ID": "Tile adjacent", "Text": "M", "Optional": ["Military"]},
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Power"},
        ],
        "Text": "You must own a Civic building adjacent to at least 2 Military buildings.\rPay 1 Influence. Increase your Power by 2.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Power"}],
    },
    {
        "Name": "Wealthy neighborhood",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile before adjacent", "Text": "H", "Optional": ["Home"]},
            {"ID": "Tile owned", "Text": "C", "Optional": ["Civic"]},
            {"ID": "Tile adjacent", "Text": "S", "Optional": ["Shop"]},
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Wealth"},
        ],
        "Text": "You must own a Civic building adjacent to at least 1 Home and at least 1 Shop.\rPay 1 Influence. Increase your Wealth by 2.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Wealth"}],
    },
    {
        "Name": "Favor of the Gods",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile before adjacent", "Text": "H", "Optional": ["Home"]},
            {"ID": "Tile owned", "Text": "C", "Optional": ["Civic"]},
            {"ID": "Tile adjacent", "Text": "T", "Optional": ["Temple"]},
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Power"},
        ],
        "Text": "You must own a Civic building adjacent to at least 1 Home and at least 1 Temple.\rPay 1 Influence. Increase your Power by 2.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Power"}],
    },
    {
        "Name": "A career in politics",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile before adjacent", "Text": "H", "Optional": ["Home"]},
            {"ID": "Tile owned", "Text": "C", "Optional": ["Civic"]},
            {"ID": "Tile adjacent", "Text": "C", "Optional": ["Civic"]},
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Wealth"},
        ],
        "Text": "You must own a Civic building adjacent to at least 1 Home and at least 1 other Civic building.\rPay 1 Influence. Increase your Wealth by 2.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Wealth"}],
    },
    {
        "Name": "Distinguished service",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile before adjacent", "Text": "H", "Optional": ["Home"]},
            {"ID": "Tile owned", "Text": "C", "Optional": ["Civic"]},
            {"ID": "Tile adjacent", "Text": "M", "Optional": ["Military"]},
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Power"},
        ],
        "Text": "You must own a Civic building adjacent to at least 1 Home and at least 1 Military building.\rPay 1 Influence. Increase your Power by 2.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Power"}],
    },
    {
        "Name": "Commercial square",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile before adjacent", "Text": "S", "Optional": ["Shop"]},
            {"ID": "Tile owned", "Text": "C", "Optional": ["Civic"]},
            {"ID": "Tile adjacent", "Text": "T", "Optional": ["Temple"]},
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Wealth"},
        ],
        "Text": "You must own a Civic building adjacent to at least 1 Shop and at least 1 Temple.\rPay 1 Influence. Increase your Wealth by 2.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Wealth"}],
    },
    {
        "Name": "Manage the town commerce",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile before adjacent", "Text": "S", "Optional": ["Shop"]},
            {"ID": "Tile owned", "Text": "C", "Optional": ["Civic"]},
            {"ID": "Tile adjacent", "Text": "C", "Optional": ["Civic"]},
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Wealth"},
        ],
        "Text": "You must own a Civic building adjacent to at least 1 Shop and at least 1 other Civic building.\rPay 1 Influence. Increase your Wealth by 2.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Wealth"}],
    },
    {
        "Name": "Supply the soldiers",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile before adjacent", "Text": "S", "Optional": ["Shop"]},
            {"ID": "Tile owned", "Text": "C", "Optional": ["Civic"]},
            {"ID": "Tile adjacent", "Text": "M", "Optional": ["Military"]},
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Power"},
        ],
        "Text": "You must own a Civic building adjacent to at least 1 Shop and at least 1 Military building.\rPay 1 Influence. Increase your Power by 2.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Power"}],
    },
    {
        "Name": "Imperial administration",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile before adjacent", "Text": "T", "Optional": ["Temple"]},
            {"ID": "Tile owned", "Text": "C", "Optional": ["Civic"]},
            {"ID": "Tile adjacent", "Text": "C", "Optional": ["Civic"]},
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Wealth"},
        ],
        "Text": "You must own a Civic building adjacent to at least 1 Temple and at least 1 other Civic building.\rPay 1 Influence. Increase your Wealth by 2.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Wealth"}],
    },
    {
        "Name": "Offerings for the soldiers",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile before adjacent", "Text": "T", "Optional": ["Temple"]},
            {"ID": "Tile owned", "Text": "C", "Optional": ["Civic"]},
            {"ID": "Tile adjacent", "Text": "M", "Optional": ["Military"]},
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Power"},
        ],
        "Text": "You must own a Civic building adjacent to at least 1 Temple and at least 1 Military building.\rPay 1 Influence. Increase your Power by 2.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Power"}],
    },
    {
        "Name": "Military administration",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile before adjacent", "Text": "C", "Optional": ["Civic"]},
            {"ID": "Tile owned", "Text": "C", "Optional": ["Civic"]},
            {"ID": "Tile adjacent", "Text": "M", "Optional": ["Military"]},
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Power"},
        ],
        "Text": "You must own a Civic building adjacent to at least 1 other Civic building and at least 1 Military building.\rPay 1 Influence. Increase your Power by 2.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Power"}],
    },
    /////////////////////////////////////////////////////////////////////
    // 5% city layout / decrease production -> power / wealth + pillar //
    /////////////////////////////////////////////////////////////////////
    {
        "Name": "Legion",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile owned", "Text": "M", "Optional": ["Military"]},
            {"ID": "Tile owned", "Text": "M", "Optional": ["Military"]},
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-5"},
            {"ID": "Metal"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Power"},
        ],
        "Tight": true,
        "Text": "You must own 2 Military buildings.\rPay 2 Influence and 5 Metal. Increase your Power by 1.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Production resource"}],
        "Trigger text": "When the card above increases your Grain, Wood, Metal, or Papyrus production, increase your Power by 1.",
        "Benefit icon": [{"ID": "Power"}],
    },
    {
        "Name": "Guild membership",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile owned", "Text": "S", "Optional": ["Shop"]},
            {"ID": "Tile owned", "Text": "S", "Optional": ["Shop"]},
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-9"},
            {"ID": "Papyrus"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Wealth"},
        ],
        "Tight": true,
        "Text": "You must own 2 Shops.\rPay 3 Influence and 9 Papyrus. Increase your Wealth by 1.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Production resource"}],
        "Trigger text": "When the card above increases your Grain, Wood, Metal, or Papyrus production, increase your Wealth by 1.",
        "Benefit icon": [{"ID": "Wealth"}],
    },
    {
        "Name": "Imperial record keeping",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Decrease production papyrus"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Wealth"},
        ],
        "Text": "Pay 3 Influence. Decrease your Papyrus production by 3. Increase your Wealth by 1.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Production resource"}],
        "Trigger text": "When the card above increases your Grain, Wood, Metal, or Papyrus production, increase your Wealth by 1.",
        "Benefit icon": [{"ID": "Wealth"}],
    },
    {
        "Name": "Seige equipment construction",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-4"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Decrease production wood"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Power"},
        ],
        "Text": "Pay 4 Influence. Decrease your Wood production by 3. Increase your Power by 1.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Production resource"}],
        "Trigger text": "When the card above increases your Grain, Wood, Metal, or Papyrus production, increase your Power by 1.",
        "Benefit icon": [{"ID": "Power"}],
    },
    {
        "Name": "Fund a welfare program",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-4"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Decrease production grain"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Power"},
        ],
        "Text": "Pay 4 Influence. Decrease your Grain production by 3. Increase your Power by 1.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Production resource"}],
        "Trigger text": "When the card above increases your Grain, Wood, Metal, or Papyrus production, increase your Power by 1.",
        "Benefit icon": [{"ID": "Power"}],
    },
    ///////////////////////
    // 10% special boons //
    ///////////////////////
    {
        "Name": "Build an amphitheatre",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-9"},
            {"ID": "Wood"},
            {"ID": "Arrow"},
            {"ID": "Place tile", "Text": "12"},
            {"ID": "Activate common card", "Text": "12"},
        ],
        "Text": "Pay 3 Influence and 9 Wood. Place an Amphitheatre tile and activate the Amphitheatre boon.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Place tile"}],
    },
    {
        "Name": "Build an amphitheatre",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-11"},
            {"ID": "Wood"},
            {"ID": "Arrow"},
            {"ID": "Place tile", "Text": "12"},
            {"ID": "Activate common card", "Text": "12"},
        ],
        "Text": "Pay 2 Influence and 11 Wood. Place an Amphitheatre tile and activate the Amphitheatre boon.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Place tile"}],
    },
    {
        "Name": "Build an Oracle",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-9"},
            {"ID": "Papyrus"},
            {"ID": "Arrow"},
            {"ID": "Place tile", "Text": "13"},
            {"ID": "Activate common card", "Text": "13"},
        ],
        "Text": "Pay 2 Influence and 9 Papyrus. Place an Oracle tile and activate the Oracle boon.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Place tile"}],
    },
    {
        "Name": "Build an Oracle",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-7"},
            {"ID": "Papyrus"},
            {"ID": "Arrow"},
            {"ID": "Place tile", "Text": "13"},
            {"ID": "Activate common card", "Text": "13"},
        ],
        "Text": "Pay 2 Influence and 7 Papyrus. Place an Oracle tile and activate the Oracle boon.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Place tile"}],
    },
    {
        "Name": "Build an Oracle",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-10"},
            {"ID": "Aureus"},
            {"ID": "Arrow"},
            {"ID": "Place tile", "Text": "13"},
            {"ID": "Activate common card", "Text": "13"},
        ],
        "Text": "Pay 3 Influence and 10 Aureus. Place an Oracle tile and activate the Oracle boon.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Place tile"}],
    },
    {
        "Name": "Build a Barracks",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-5"},
            {"ID": "Metal"},
            {"ID": "Arrow"},
            {"ID": "Place tile", "Text": "14", "Optional": ["Military"]},
            {"ID": "Activate common card", "Text": "14"},
        ],
        "Text": "Pay 3 Influence and 5 Metal. Place a Barracks tile and activate the Barracks boon.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Place tile", "Optional": ["Military"]}],
    },
    {
        "Name": "Build a Barracks",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-7"},
            {"ID": "Metal"},
            {"ID": "Arrow"},
            {"ID": "Place tile", "Text": "14", "Optional": ["Military"]},
            {"ID": "Activate common card", "Text": "14"},
        ],
        "Text": "Pay 2 Influence and 7 Metal. Place a Barracks tile and activate the Barracks boon.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Place tile", "Optional": ["Military"]}],
    },
    {
        "Name": "Build a Barracks",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-10"},
            {"ID": "Grain"},
            {"ID": "Arrow"},
            {"ID": "Place tile", "Text": "14", "Optional": ["Military"]},
            {"ID": "Activate common card", "Text": "14"},
        ],
        "Text": "Pay 2 Influence and 10 Grain. Place a Barracks tile and activate the Barracks boon.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Place tile", "Optional": ["Military"]}],
    },
    {
        "Name": "Build a Parade",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-5"},
            {"ID": "Metal"},
            {"ID": "Pay amount", "Text": "-5"},
            {"ID": "Papyrus"},
            {"ID": "Arrow"},
            {"ID": "Place tile", "Text": "15", "Optional": ["Military"]},
            {"ID": "Activate common card", "Text": "15"},
        ],
        "Text": "Pay 5 Metal and 5 Papyrus. Place a Parade tile and activate the Parade boon.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Place tile", "Optional": ["Military"]}],
    },
    {
        "Name": "Build a Parade",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-7"},
            {"ID": "Metal"},
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Papyrus"},
            {"ID": "Arrow"},
            {"ID": "Place tile", "Text": "15", "Optional": ["Military"]},
            {"ID": "Activate common card", "Text": "15"},
        ],
        "Text": "Pay 7 Metal and 3 Papyrus. Place a Parade tile and activate the Parade boon.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Place tile", "Optional": ["Military"]}],
    },
    ////////////////////
    // 10% draw cards //
    ////////////////////
    {
        "Name": "Fortunate encounter",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Opportunity card"},
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Discard card"},
        ],
        "Text": "Pay 1 Influence. Draw 2 Opportunity cards, then discard 1 card from your hand.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Opportunity card"}],
    },
    {
        "Name": "Fortunate encounter",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Opportunity card"},
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Discard card"},
        ],
        "Text": "Pay 1 Influence. Draw 2 Opportunity cards, then discard 1 card from your hand.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Opportunity card"}],
    },
    {
        "Name": "Family acquaintance",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Opportunity card"},
        ],
        "Text": "Pay 1 Influence. Draw 2 Opportunity cards.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Opportunity card"}],
    },
    {
        "Name": "Family acquaintance",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Opportunity card"},
        ],
        "Text": "Pay 1 Influence. Draw 2 Opportunity cards.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Opportunity card"}],
    },
    {
        "Name": "Trip to Florence",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "=4"},
            {"ID": "Opportunity card"},
        ],
        "Text": "Pay 2 Influence. Draw Opportunity cards until you have 4 cards in your hand.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Opportunity card"}],
    },
    {
        "Name": "Trip to Florence",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "=4"},
            {"ID": "Opportunity card"},
        ],
        "Text": "Pay 2 Influence. Draw Opportunity cards until you have 4 cards in your hand.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Opportunity card"}],
    },
    {
        "Name": "Trip to Rome",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-4"},
            {"ID": "Aureus"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "=6"},
            {"ID": "Opportunity card"},
        ],
        "Text": "Pay 2 Influence and 4 Aureus. Draw Opportunity cards until you have 6 cards in your hand.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Opportunity card"}],
    },
    {
        "Name": "Trip to Rome",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-4"},
            {"ID": "Aureus"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "=6"},
            {"ID": "Opportunity card"},
        ],
        "Text": "Pay 2 Influence and 4 Aureus. Draw Opportunity cards until you have 6 cards in your hand.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Opportunity card"}],
    },
    {
        "Name": "Pious reputation",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Metal"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+4"},
            {"ID": "Opportunity card"},
            {"ID": "Pay amount", "Text": "=4"},
            {"ID": "Discard card"},
        ],
        "Text": "Pay 1 Influence and 3 Metal. Draw 4 Opportunity cards, then discard until you have 4 or fewer cards in your hand.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Opportunity card"}],
    },
    {
        "Name": "Prestigious reputation",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Papyrus"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+4"},
            {"ID": "Opportunity card"},
            {"ID": "Pay amount", "Text": "=4"},
            {"ID": "Discard card"},
        ],
        "Text": "Pay 1 Influence and 3 Papyrus. Draw 4 Opportunity cards, then discard until you have 4 or fewer cards in your hand.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Opportunity card"}],
    },
    ////////////////////////////
    // 5% draw cards + pillar //
    ////////////////////////////
    {
        "Name": "Family succession",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-4"},
            {"ID": "Papyrus"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Opportunity card"},
        ],
        "Text": "Pay 1 Influence and 4 Papyrus. Draw an Opportunity card.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Power"}],
        "Trigger text": "When the card above increases your Power, draw an Opportunity card.",
        "Benefit icon": [{"ID": "Opportunity card"}],
    },
    {
        "Name": "Designate an heir",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-4"},
            {"ID": "Metal"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Opportunity card"},
        ],
        "Text": "Pay 1 Influence and 4 Metal. Draw an Opportunity card.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Wealth"}],
        "Trigger text": "When the card above increases your Wealth, draw an Opportunity card.",
        "Benefit icon": [{"ID": "Opportunity card"}],
    },
    {
        "Name": "Entrepreneurship",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Grain"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Opportunity card"},
        ],
        "Text": "Pay 2 Influence and 3 Grain. Draw 2 Opportunity cards.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Production resource"}],
        "Trigger text": "When the card above increases your Grain, Wood, Metal, or Papyrus production, draw an Opportunity card.",
        "Benefit icon": [{"ID": "Opportunity card"}],
    },
    {
        "Name": "Friendly neighbors",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-4"},
            {"ID": "Wood"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Opportunity card"},
        ],
        "Text": "Pay 2 Influence and 4 Wood. Draw 2 Opportunity cards.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Place tile", "Optional": ["Multi"]}],
        "Trigger text": "When the card above places a tile, draw an Opportunity card.",
        "Benefit icon": [{"ID": "Opportunity card"}],
    },
    {
        "Name": "Confident negotiation",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-4"},
            {"ID": "Papyrus"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Opportunity card"},
        ],
        "Text": "Pay 2 Influence and 4 Papyrus. Draw an Opportunity card.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Opportunity set"}],
        "Trigger text": "When the card above takes an Opportunity set, draw an Opportunity card.",
        "Benefit icon": [{"ID": "Opportunity card"}],
    },
    ////////////////////////////////
    // 5% extra common, buy, sell //
    ////////////////////////////////
    {
        "Name": "Extra Common project",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-X"},
            {"ID": "Resource"},
            {"ID": "Arrow"},
            {"ID": "Place tile", "Text": "X", "Optional": ["Multi"]}
        ],
        "Text": "Pay 1 Influence. Build a Common project.",
        "End": "Return",
        "Benefit icon": [{"ID": "Place tile", "Optional": ["Multi"]}],
    },
    {
        "Name": "Extra Common project",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-X"},
            {"ID": "Resource"},
            {"ID": "Arrow"},
            {"ID": "Place tile", "Text": "X", "Optional": ["Multi"]}
        ],
        "Text": "Pay 1 Influence. Build a Common project.",
        "End": "Return",
        "Benefit icon": [{"ID": "Place tile", "Optional": ["Multi"]}],
    },
    {
        "Name": "Extra buy resources",
        "Type": "Starting",
        "Order": "Player",
        "Icons": [
            {"ID": "Market up"},
            {"ID": "Pay amount", "Text": "-X"},
            {"ID": "Aureus"},
            {"ID": "Multi arrow"},
            {"ID": "Gain amount", "Text": "+5"},
            {"ID": "Resource"},
        ],
        "Text": "Increase the price marker of any resource in the Market by one level. Pay the new price in Aureus and gain 5 of that resource.\rRepeat as many times as you want for the same resource.",
        "End": "Return",
        "Benefit icon": [{"ID": "Resource"}],
    },
    {
        "Name": "Extra buy resources",
        "Type": "Starting",
        "Order": "Player",
        "Icons": [
            {"ID": "Market up"},
            {"ID": "Pay amount", "Text": "-X"},
            {"ID": "Aureus"},
            {"ID": "Multi arrow"},
            {"ID": "Gain amount", "Text": "+5"},
            {"ID": "Resource"},
        ],
        "Text": "Increase the price marker of any resource in the Market by one level. Pay the new price in Aureus and gain 5 of that resource.\rRepeat as many times as you want for the same resource.",
        "End": "Return",
        "Benefit icon": [{"ID": "Resource"}],
    },
    {
        "Name": "Extra sell resources",
        "Type": "Starting",
        "Order": "Player",
        "Icons": [
            {"ID": "Market down"},
            {"ID": "Pay amount", "Text": "-5"},
            {"ID": "Resource"},
            {"ID": "Multi arrow"},
            {"ID": "Gain amount", "Text": "+X"},
            {"ID": "Aureus"},
        ],
        "Text": "Decrease the price marker of any resource in the Market by one level. Pay 5 of that resource and gain the new price in Aureus.\rRepeat as many times as you want for the same resource.",
        "End": "Return",
        "Benefit icon": [{"ID": "Aureus"}],
    },
    ////////////////
    // 5% special //
    ////////////////
    {
        "Name": "Favorable contract",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-X"},
            {"ID": "Aureus"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+6"},
            {"ID": "Resource"},
        ],
        "Text": "Pick any resource. Pay its current market price in Aurues and gain 6 of that resource.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Resource"}],
    },
    {
        "Name": "Villa",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Grain"},
            {"ID": "Arrow"},
            {"ID": "Place tile", "Text": "H1", "Optional": ["Home"]},
        ],
        "Text": "Pay 1 Influence and 2 Grain. Place a Domas tile on any free space along the edge of the city.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Place tile", "Optional": ["Home"]}],
    },
    {
        "Name": "Meditation and focus",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-X"},
            {"ID": "Discard card"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2X"},
            {"ID": "Influence"},
        ],
        "Text": "Discard any number of cards from your hand. Gain 2 Influence for each discarded card.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Influence"}],
    },
    {
        "Name": "Market manipulation",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Market up"},
            {"ID": "Market down"},
        ],
        "Text": "Pay 1 Influence. In the Market, increase a resource's price marker one level, and decrease a different resource's price marker one level.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Market up"}],
    },
    {
        "Name": "Foresight",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+X"},
            {"ID": "Aureus"},
        ],
        "Text": "Pay 1 Influence. Gain 1 Aureus for each card in your hand (not including this one).",
        "End": "Remove",
        "Benefit icon": [{"ID": "Aureus"}],
    },
];

var  cardInfo = [];

var colors = [
    "Red",
    "Blue",
    "Green",
    "Purple",
    "Orange",
    "Cyan",
]

for (var i = 0; i < colors.length; i++) {
    for (var j = 0; j < startingCardInfo.length; j++) {
        var card = copyObj(startingCardInfo[j]);
        card["Type"] = "Starting";
        card["Player"] = colors[i];
        cardInfo.push(card);
    }
}

function copyObj(input) {
    var output = {};
    for (key in input) {
        output[key] = input[key];
    }
    return output;
}

var compass = [
    "N",
    "S",
    "W",
    "E",
];
var ci = 0;

for (var i = 0; i < opportunityCardInfo.length; i++) {
    opportunityCardInfo[i]["Compass"] = compass[ci];
    ci++;
    ci = ci % 4;
    opportunityCardInfo[i]["Type"] = "Opportunity";
    cardInfo.push(opportunityCardInfo[i])
}