var startingCardInfo = [
    {
        "Name": "Take an Opportunity set",
        "Type": "Starting",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-3/12"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "1/2"},
            {"ID": "Opportunity set"}
        ],
        "Text": "Do either of the following:\r - Pay 3 Influence. Take an Opportunity set.\r - Pay 12 Influence. Take 2 Opportunity sets.",
        "End": "Return",
        "Benefit icon": [{"ID": "Opportunity set"}],
    },
    {
        "Name": "Common projects",
        "Type": "Starting",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1/4/9"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-X"},
            {"ID": "Resource"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "1/2/3"},
            {"ID": "Place tile",    "Text": "X"}
        ],
        "Text": "Do any one of the following:\r - Pay 1 Influence. Build a Common project.\r - Pay 4 Influence. Build 2 Common projects.\r - Pay 9 Influence. Build 3 Common projects.",
        "End": "Return",
        "Benefit icon": [{"ID": "Place tile"}],
    },
    {
        "Name": "Buy resources",
        "Type": "Starting",
        "Order": "Player",
        "Icons": [
            {"ID": "Market up"},
            {"ID": "Pay amount", "Text": "-X"},
            {"ID": "Aureus"},
            {"ID": "Multi arrow"},
            {"ID": "Gain amount", "Text": "+5"},
            {"ID": "Resource"},
        ],
        "Text": "Increase the price marker of any resource in the Market by one level. Pay the new price in Aureus and gain 5 of that resource.\rRepeat as many times as you want for the same resource.",
        "End": "Return",
        "Benefit icon": [{"ID": "Resource"}],
    },
    {
        "Name": "Sell resources",
        "Type": "Starting",
        "Order": "Player",
        "Icons": [
            {"ID": "Market down"},
            {"ID": "Pay amount", "Text": "-5"},
            {"ID": "Resource"},
            {"ID": "Multi arrow"},
            {"ID": "Gain amount", "Text": "+X"},
            {"ID": "Aureus"},
        ],
        "Text": "Decrease the price marker of any resource in the Market by one level. Pay 5 of that resource and gain the new price in Aureus.\rRepeat as many times as you want for the same resource.",
        "End": "Return",
        "Benefit icon": [{"ID": "Aureus"}],
    },
];

var opportunityCardInfo = [

    // 20% Pillar builders
    {
        "Name": "Supply food for Rome",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Grain"},
            {"ID": "Arrow"          },
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Aureus"},
        ],
        "Text": "Pay 2 Influence and 3 Grain. Gain 1 Aureus.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Resource"}],
        "Trigger text": "When the card above gains Grain, Wood, Metal, or Papyrus, gain 1 Aureus.",
        "Benefit icon": [{"ID": "Aureus"}],
    },
    {
        "Name": "Control the dockyard",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-5"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-18"},
            {"ID": "Metal"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Wealth"},
        ],
        "Text": "Pay 5 Influence and 18 Metal. Increase your Wealth by 1.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Production resource"}],
        "Trigger text": "When the card above increases Grain, Wood, Metal, or Papyrus production, increase your Wealth by 1.",
        "Benefit icon": [{"ID": "Wealth"}],
    },
    {
        "Name": "Wealthy relatives",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+4"},
            {"ID": "Metal"},
        ],
        "Text": "Pay 3 Influence. Gain 4 Metal.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Wealth"}],
        "Trigger text": "When the card above increases your Wealth, gain 1 Metal.",
        "Benefit icon": [{"ID": "Metal"}],
    },
    {
        "Name": "Foreign connections",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+3"},
            {"ID": "Papyrus"},
        ],
        "Text": "Pay 2 Influence. Gain 3 Papyrus.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Power"}],
        "Trigger text": "When the card above increases your Power, gain 1 Papyrus.",
        "Benefit icon": [{"ID": "Papyrus"}],
    },
    {
        "Name": "Presitigious architecture",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-4"},
            {"ID": "Papyrus"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+6"},
            {"ID": "Aureus"},
        ],
        "Text": "Pay 2 Influence and 4 Papyrus. Gain 6 Aureus.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Place tile"}],
        "Trigger text": "When the card above places a tile, gain 1 Aureus.",
        "Benefit icon": [{"ID": "Aureus"}],
    },
    {
        "Name": "Resource management",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+3"},
            {"ID": "Wood"},
        ],
        "Text": "Pay 3 Influence. Gain 3 Wood.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Aureus"}],
        "Trigger text": "When the card above gains Aureus, gain 1 Wood.",
        "Benefit icon": [{"ID": "Wood"}],
    },
    {
        "Name": "Join the farmer's guild",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-4"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+4"},
            {"ID": "Grain"},
        ],
        "Text": "Pay 4 Influence. Gain 4 Grain.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Opportunity set"}],
        "Trigger text": "When the card above takes an Opportunity set, gain 1 Grain.",
        "Benefit icon": [{"ID": "Grain"}],
    },
    {
        "Name": "Double entry accounting",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-6"},
            {"ID": "Papyrus"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+3"},
            {"ID": "Aureus"},
        ],
        "Text": "Pay 2 Influence and 6 Papyrus. Gain 3 Aureus.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Resource"}],
        "Trigger text": "When the card above gains Grain, Wood, Metal, or Papyrus, gain 1 Aureus.",
        "Benefit icon": [{"ID": "Aureus"}],
    },
    {
        "Name": "Fine tools",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-10"},
            {"ID": "Metal"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Production papyrus"},
        ],
        "Text": "Pay 3 Influence and 10 Metal. Increase your Papyrus production by 1.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Wealth"}],
        "Trigger text": "When the card above increases your Wealth, increase your Papyrus production by 1.",
        "Benefit icon": [{"ID": "Production papyrus"}],
    },
    {
        "Name": "Water wheel",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-7"},
            {"ID": "Wood"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+8"},
            {"ID": "Grain"},
        ],
        "Text": "Pay 2 Influence and 7 Wood. Gain 8 Grain.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Opportunity set"}],
        "Trigger text": "When the card above takes an Opportunity set, gain 1 Grain.",
        "Benefit icon": [{"ID": "Grain"}],
    },
    {
        "Name": "Country estate",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-8"},
            {"ID": "Papyrus"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Production wood"},
        ],
        "Text": "Pay 3 Influence and 8 Papyrus. Increase your Wood production by 1.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Power"}],
        "Trigger text": "When the card above increases your Power, increase your Wood production by 1.",
        "Benefit icon": [{"ID": "Production wood"}],
    },
    {
        "Name": "Smelting",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-9"},
            {"ID": "Metal"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Production metal"},
        ],
        "Text": "Pay 3 Influence and 9 Metal. Increase your Metal production by 1.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Production resource"}],
        "Trigger text": "When the card above increases your Grain, Wood, Metal, or Papyrus prodution, increase your Metal production by 1.",
        "Benefit icon": [{"ID": "Production metal"}],
    },
    {
        "Name": "Connection with the guilds",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-5"},
            {"ID": "Metal"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+5"},
            {"ID": "Aureus"},
        ],
        "Text": "Pay 2 Influence and 5 Metal. Gain 5 Aureus.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Resource"}],
        "Trigger text": "When the card above gains Grain, Wood, Metal, or Papyrus, gain 1 Aureus.",
        "Benefit icon": [{"ID": "Aureus"}],
    },
    {
        "Name": "Family succession",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-8"},
            {"ID": "Papyrus"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Opportunity card"},
        ],
        "Text": "Pay 1 Influence and 8 Papyrus. Draw an Opportunity card.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Power"}],
        "Trigger text": "When the card above increases your Power, draw an Opportunity card.",
        "Benefit icon": [{"ID": "Opportunity card"}],
    },
    {
        "Name": "Experimental crops",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Decrease production grain"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+6"},
            {"ID": "Grain"},
        ],
        "Text": "Reduce your Grain production by 1. Gain 6 Grain.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Production resource"}],
        "Trigger text": "When the card above increases your Grain, Wood, Metal, or Papyrus production, gain 1 Grain.",
        "Benefit icon": [{"ID": "Grain"}],
    },
    {
        "Name": "Reused cellar barrels",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Decrease production wood"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+6"},
            {"ID": "Wood"},
        ],
        "Text": "Reduce your Wood production by 1. Gain 6 Wood.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Production resource"}],
        "Trigger text": "When the card above increases your Grain, Wood, Metal, or Papyrus production, gain 1 Wood.",
        "Benefit icon": [{"ID": "Wood"}],
    },
    {
        "Name": "Merchant ship contract",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+3"},
            {"ID": "Metal"},
        ],
        "Text": "Pay 3 Influence. Gain 3 Metal.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Resource"}],
        "Trigger text": "When the card above gains Grain, Wood, Metal, or Papyrus, gain 1 Metal.",
        "Benefit icon": [{"ID": "Metal"}],
    },
    {
        "Name": "Lecture at the University",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+3"},
            {"ID": "Papyrus"},
        ],
        "Text": "Pay 3 Influence. Gain 3 Papyrus.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Resource"}],
        "Trigger text": "When the card above gains Grain, Wood, Metal, or Papyrus, gain 1 Papyrus.",
        "Benefit icon": [{"ID": "Papyrus"}],
    },
    {
        "Name": "Deal with the baker",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Grain"},
        ],
        "Text": "Pay 3 Influence. Gain 2 Grain.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Aureus"}],
        "Trigger text": "When the card above gains Aureus, gain 1 Grain.",
        "Benefit icon": [{"ID": "Grain"}],
    },
    {
        "Name": "Construction techniques",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Wood"},
        ],
        "Text": "Pay 2 Influence. Gain 2 Wood.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Place tile"}],
        "Trigger text": "When the card above places a tile, gain 1 Wood.",
        "Benefit icon": [{"ID": "Wood"}],
    },

    // 10% direct resource and aureus givers
    {
        "Name": "Feast",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+6"},
            {"ID": "Grain"},
        ],
        "Text": "Pay 1 Influence. Gain 6 Grain.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Grain"}],
    },
    {
        "Name": "Lumber cache",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+5"},
            {"ID": "Wood"},
        ],
        "Text": "Pay 1 Influence. Gain 5 Wood.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Wood"}],
    },
    {
        "Name": "Plenty",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+9"},
            {"ID": "Grain"},
        ],
        "Text": "Pay 2 Influence. Gain 9 Grain.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Grain"}],
    },
    {
        "Name": "Firewood",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+8"},
            {"ID": "Wood"},
        ],
        "Text": "Pay 2 Influence. Gain 8 Wood.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Wood"}],
    },
    {
        "Name": "Minor mineral discovery",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+6"},
            {"ID": "Metal"},
        ],
        "Text": "Pay 2 Influence. Gain 6 Metal.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Metal"}],
    },
    {
        "Name": "Host a poetry reading",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+6"},
            {"ID": "Papyrus"},
        ],
        "Text": "Pay 2 Influence. Gain 6 Papyrus.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Papyrus"}],
    },
    {
        "Name": "Major mineral discovery",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+10"},
            {"ID": "Metal"},
        ],
        "Text": "Pay 3 Influence. Gain 10 Metal.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Metal"}],
    },
    {
        "Name": "Support academics",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+10"},
            {"ID": "Papyrus"},
        ],
        "Text": "Pay 3 Influence. Gain 10 Papyrus.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Papyrus"}],
    },
    {
        "Name": "A Senator's favor",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+10"},
            {"ID": "Aureus"},
        ],
        "Text": "Pay 2 Influence. Gain 10 Aureus.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Aureus"}],
    },
    {
        "Name": "Festival",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-4"},
            {"ID": "Metal"},
            {"ID": "Arrow"},
            {"ID": "Tile anyone", "Text": "T"},
            {"ID": "Gain amount", "Text": "+3x"},
            {"ID": "Aureus"},
        ],
        "Text": "Pay 1 Influence and 4 Metal. Gain 3 Aureus for each Temple in the city.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Aureus"}],
    },

    // 15% resource production
    {
        "Name": "Farming techniques",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-4"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Production grain"},
        ],
        "Text": "Pay 4 Influence. Increase your Grain production by 2.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Production grain"}],
    },
    {
        "Name": "Preferred customer",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile owned", "Text": "H"},
            {"ID": "Tile adjacent", "Text": "S"},
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Production grain"},
        ],
        "Text": "You must own a Home adjacent to at least 1 Shop.\rPay 2 Influence. Increase your Grain production by 2.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Production grain"}],
    },
    {
        "Name": "Replanting crops",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Grain"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Production grain"},
        ],
        "Text": "Pay 2 Influence and 2 Grain. Increase your Grain production by 1.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Production grain"}],
    },
    {
        "Name": "Logging techniques",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Production wood"},
        ],
        "Text": "Pay 3 Influence. Increase your Wood production by 1.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Production wood"}],
    },
    {
        "Name": "Selective cutting",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Wood"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Production wood"},
        ],
        "Text": "Pay 2 Influence and 2 Wood. Increase your Wood production by 1.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Production wood"}],
    },
    {
        "Name": "Mining techniques",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Production metal"},
        ],
        "Text": "Pay 3 Influence. Increase your Metal production by 1.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Production metal"}],
    },
    {
        "Name": "Mining equipment",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Metal"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Production metal"},
        ],
        "Text": "Pay 2 Influence and 2 Metal. Increase your Metal production by 1.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Production metal"}],
    },
    {
        "Name": "Paperforming techniques",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Production papyrus"},
        ],
        "Text": "Pay 3 Influence. Increase your Papyrus production by 1.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Production papyrus"}],
    },
    {
        "Name": "Paperforming training",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Papyrus"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Production papyrus"},
        ],
        "Text": "Pay 2 Influence and 2 Papyrus. Increase your Papyrus production by 1.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Production papyrus"}],
    },
    {
        "Name": "Selective breeding",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-8"},
            {"ID": "Aureus"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Production grain"},
        ],
        "Text": "Pay 3 Influence and 8 Aureus. Increase your Grain production by 2.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Production grain"}],
    },
    {
        "Name": "Aquaduct lumber transport",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-8"},
            {"ID": "Aureus"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Production wood"},
        ],
        "Text": "Pay 3 Influence and 8 Aureus. Increase your Wood production by 2.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Production wood"}],
    },
    {
        "Name": "Smithery expertise",
        "Type": "Immediate",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-4"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-10"},
            {"ID": "Aureus"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Production metal"},
        ],
        "Text": "Pay 4 Influence and 10 Aureus. Increase your Metal production by 2.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Production metal"}],
    },
    {
        "Name": "Acta diurna",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-4"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-10"},
            {"ID": "Aureus"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Production papyrus"},
        ],
        "Text": "Pay 4 Influence and 10 Aureus. Increase your Papyrus production by 2.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Production papyrus"}],
    },
    {
        "Name": "Connections with neighbors",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile owned", "Text": "H"},
            {"ID": "Tile adjacent", "Text": "C"},
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Production resource"},
        ],
        "Text": "You must own a Home adjacent to at least 1 Civic building.\rPay 3 Influence. Increase your Grain, Wood, Metal, or Papyrus production by 1.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Production resource"}],
    },
    {
        "Name": "Business accument",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile owned", "Text": "S"},
            {"ID": "Tile adjacent", "Text": "C"},
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Production resource"},
        ],
        "Text": "You must own a Shop adjacent to at least 1 Civic building.\rPay 3 Influence. Increase your Grain, Wood, Metal, or Papyrus production by 1.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Production resource"}],
    },

    // 10% direct power and wealth
    {
        "Name": "Lead a cohort",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-5"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-12"},
            {"ID": "Metal"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Power"},
        ],
        "Text": "Pay 5 Influence and 12 Metal. Increase your Power by 1.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Power"}],
    },
    {
        "Name": "Political circles",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-5"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-15"},
            {"ID": "Aureus"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Power"},
        ],
        "Text": "Pay 5 Influence and 15 Aureus. Increase your Power by 1.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Power"}],
    },
    {
        "Name": "Political marriage",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-5"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-12"},
            {"ID": "Grain"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Wealth"},
        ],
        "Text": "Pay 5 Influence and 12 Grain. Increase your Wealth by 1.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Wealth"}],
    },
    {
        "Name": "Business partnerships",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-5"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-15"},
            {"ID": "Aureus"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Wealth"},
        ],
        "Text": "Pay 5 Influence and 15 Aureus. Increase your Wealth by 1.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Wealth"}],
    },
    {
        "Name": "Bonfire celebration",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-12"},
            {"ID": "Wood"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Wealth"},
        ],
        "Text": "Pay 3 Influence and 12 Wood. Increase your Wealth by 1.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Wealth"}],
    },
    {
        "Name": "Legion",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-7"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-20"},
            {"ID": "Metal"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Power"},
        ],
        "Text": "Pay 7 Influence and 20 Metal. Increase your Power by 2.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Power"}],
    },
    {
        "Name": "Guild membership",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-7"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-20"},
            {"ID": "Papyrus"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Wealth"},
        ],
        "Text": "Pay 7 Influence and 20 Papyrus. Increase your Wealth by 2.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Wealth"}],
    },
    {
        "Name": "Imperial record keeping",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Decrease production papyrus"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Wealth"},
        ],
        "Text": "Decrease your Papyrus production by 2. Increase your Wealth by 2.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Wealth"}],
    },
    {
        "Name": "Seige equipment construction",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Decrease production wood"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Power"},
        ],
        "Text": "Decrease your Wood production by 2. Increase your Power by 2.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Power"}],
    },
    {
        "Name": "Fund a welfare program",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-6"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Decrease production grain"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+3"},
            {"ID": "Power"},
        ],
        "Text": "Pay 6 Influence. Decrease your Grain production by 2. Increase your Power by 3.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Power"}],
    },

    // 15% power and wealth from city layout
    {
        "Name": "Improve literacy",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile before adjacent", "Text": "H"},
            {"ID": "Tile owned", "Text": "C"},
            {"ID": "Tile adjacent", "Text": "H"},
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Wealth"},
        ],
        "Text": "You must own a Civic building adjacent to at least 2 Homes.\rPay 2 Influence. Increase your Wealth by 2.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Wealth"}],
    },
    {
        "Name": "Magnate",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile before adjacent", "Text": "S"},
            {"ID": "Tile owned", "Text": "C"},
            {"ID": "Tile adjacent", "Text": "S"},
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Wealth"},
        ],
        "Text": "You must own a Civic building adjacent to at least 2 Shops.\rPay 2 Influence. Increase your Wealth by 2.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Wealth"}],
    },
    {
        "Name": "Pious",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile before adjacent", "Text": "T"},
            {"ID": "Tile owned", "Text": "C"},
            {"ID": "Tile adjacent", "Text": "T"},
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Power"},
        ],
        "Text": "You must own a Civic building adjacent to at least 2 Temples.\rPay 2 Influence. Increase your Power by 2.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Power"}],
    },
    {
        "Name": "Civic square",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile before adjacent", "Text": "C"},
            {"ID": "Tile owned", "Text": "C"},
            {"ID": "Tile adjacent", "Text": "C"},
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+3"},
            {"ID": "Wealth"},
        ],
        "Text": "You must own a Civic building adjacent to at least 2 other Civic buildings.\rPay 3 Influence. Increase your Wealth by 3.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Wealth"}],
    },
    {
        "Name": "Record history",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile before adjacent", "Text": "M"},
            {"ID": "Tile owned", "Text": "C"},
            {"ID": "Tile adjacent", "Text": "M"},
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+3"},
            {"ID": "Power"},
        ],
        "Text": "You must own a Civic building adjacent to at least 2 Military buildings.\rPay 3 Influence. Increase your Power by 3.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Power"}],
    },
    {
        "Name": "Wealthy neighborhood",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile before adjacent", "Text": "H"},
            {"ID": "Tile owned", "Text": "C"},
            {"ID": "Tile adjacent", "Text": "S"},
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Wealth"},
        ],
        "Text": "You must own a Civic building adjacent to at least 1 Home and at least 1 Shop.\rPay 2 Influence. Increase your Wealth by 2.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Wealth"}],
    },
    {
        "Name": "Favor of the Gods",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile before adjacent", "Text": "H"},
            {"ID": "Tile owned", "Text": "C"},
            {"ID": "Tile adjacent", "Text": "T"},
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Power"},
        ],
        "Text": "You must own a Civic building adjacent to at least 1 Home and at least 1 Temple.\rPay 2 Influence. Increase your Power by 2.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Power"}],
    },
    {
        "Name": "A career in politics",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile before adjacent", "Text": "H"},
            {"ID": "Tile owned", "Text": "C"},
            {"ID": "Tile adjacent", "Text": "C"},
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+3"},
            {"ID": "Wealth"},
        ],
        "Text": "You must own a Civic building adjacent to at least 1 Home and at least 1 other Civic building.\rPay 3 Influence. Increase your Wealth by 3.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Wealth"}],
    },
    {
        "Name": "Distinguished service",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile before adjacent", "Text": "H"},
            {"ID": "Tile owned", "Text": "C"},
            {"ID": "Tile adjacent", "Text": "M"},
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+3"},
            {"ID": "Power"},
        ],
        "Text": "You must own a Civic building adjacent to at least 1 Home and at least 1 Military building.\rPay 3 Influence. Increase your Power by 3.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Power"}],
    },
    {
        "Name": "Commercial square",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile before adjacent", "Text": "S"},
            {"ID": "Tile owned", "Text": "C"},
            {"ID": "Tile adjacent", "Text": "T"},
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Wealth"},
        ],
        "Text": "You must own a Civic building adjacent to at least 1 Shop and at least 1 Temple.\rPay 2 Influence. Increase your Wealth by 2.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Wealth"}],
    },
    {
        "Name": "Manage the town commerce",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile before adjacent", "Text": "S"},
            {"ID": "Tile owned", "Text": "C"},
            {"ID": "Tile adjacent", "Text": "C"},
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Wealth"},
        ],
        "Text": "You must own a Civic building adjacent to at least 1 Shop and at least 1 other Civic building.\rPay 2 Influence. Increase your Wealth by 2.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Wealth"}],
    },
    {
        "Name": "Supply the soldiers",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile before adjacent", "Text": "S"},
            {"ID": "Tile owned", "Text": "C"},
            {"ID": "Tile adjacent", "Text": "M"},
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+3"},
            {"ID": "Power"},
        ],
        "Text": "You must own a Civic building adjacent to at least 1 Shop and at least 1 Military building.\rPay 3 Influence. Increase your Power by 3.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Power"}],
    },
    {
        "Name": "Imperial administration",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile before adjacent", "Text": "T"},
            {"ID": "Tile owned", "Text": "C"},
            {"ID": "Tile adjacent", "Text": "C"},
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+3"},
            {"ID": "Wealth"},
        ],
        "Text": "You must own a Civic building adjacent to at least 1 Temple and at least 1 other Civic building.\rPay 3 Influence. Increase your Wealth by 3.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Wealth"}],
    },
    {
        "Name": "Offerings for the soldiers",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile before adjacent", "Text": "T"},
            {"ID": "Tile owned", "Text": "C"},
            {"ID": "Tile adjacent", "Text": "M"},
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+3"},
            {"ID": "Power"},
        ],
        "Text": "You must own a Civic building adjacent to at least 1 Temple and at least 1 Military building.\rPay 3 Influence. Increase your Power by 3.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Power"}],
    },
    {
        "Name": "Military administration",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Tile before adjacent", "Text": "C"},
            {"ID": "Tile owned", "Text": "C"},
            {"ID": "Tile adjacent", "Text": "M"},
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+3"},
            {"ID": "Power"},
        ],
        "Text": "You must own a Civic building adjacent to at least 1 other Civic building and at least 1 Military building.\rPay 3 Influence. Increase your Power by 3.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Power"}],
    },

    // 10% direct Boons
    {
        "Name": "Build an amphitheatre",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-5"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-18"},
            {"ID": "Wood"},
            {"ID": "Arrow"},
            {"ID": "Place tile", "Text": "12"},
            {"ID": "Activate common card", "Text": "12"},
        ],
        "Text": "Pay 5 Influence and 18 Wood. Place an Amphitheatre tile and activate the Amphitheatre boon.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Place tile"}],
    },
    {
        "Name": "Build an amphitheatre",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-4"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-22"},
            {"ID": "Wood"},
            {"ID": "Arrow"},
            {"ID": "Place tile", "Text": "12"},
            {"ID": "Activate common card", "Text": "12"},
        ],
        "Text": "Pay 4 Influence and 22 Wood. Place an Amphitheatre tile and activate the Amphitheatre boon.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Place tile"}],
    },
    {
        "Name": "Build an Oracle",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-18"},
            {"ID": "Papyrus"},
            {"ID": "Arrow"},
            {"ID": "Place tile", "Text": "13"},
            {"ID": "Activate common card", "Text": "13"},
        ],
        "Text": "Pay 3 Influence and 18 Papyrus. Place an Oracle tile and activate the Oracle boon.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Place tile"}],
    },
    {
        "Name": "Build an Oracle",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-4"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-14"},
            {"ID": "Papyrus"},
            {"ID": "Arrow"},
            {"ID": "Place tile", "Text": "13"},
            {"ID": "Activate common card", "Text": "13"},
        ],
        "Text": "Pay 4 Influence and 14 Papyrus. Place an Oracle tile and activate the Oracle boon.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Place tile"}],
    },
    {
        "Name": "Build an Oracle",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-5"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-20"},
            {"ID": "Aureus"},
            {"ID": "Arrow"},
            {"ID": "Place tile", "Text": "13"},
            {"ID": "Activate common card", "Text": "13"},
        ],
        "Text": "Pay 5 Influence and 20 Aureus. Place an Oracle tile and activate the Oracle boon.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Place tile"}],
    },
    {
        "Name": "Build a Barracks",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-5"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-10"},
            {"ID": "Metal"},
            {"ID": "Arrow"},
            {"ID": "Place tile", "Text": "14"},
            {"ID": "Activate common card", "Text": "14"},
        ],
        "Text": "Pay 5 Influence and 10 Metal. Place a Barracks tile and activate the Barracks boon.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Place tile"}],
    },
    {
        "Name": "Build a Barracks",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-4"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-14"},
            {"ID": "Metal"},
            {"ID": "Arrow"},
            {"ID": "Place tile", "Text": "14"},
            {"ID": "Activate common card", "Text": "14"},
        ],
        "Text": "Pay 4 Influence and 14 Metal. Place a Barracks tile and activate the Barracks boon.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Place tile"}],
    },
    {
        "Name": "Build a Barracks",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-4"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-20"},
            {"ID": "Grain"},
            {"ID": "Arrow"},
            {"ID": "Place tile", "Text": "14"},
            {"ID": "Activate common card", "Text": "14"},
        ],
        "Text": "Pay 4 Influence and 20 Grain. Place a Barracks tile and activate the Barracks boon.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Place tile"}],
    },
    {
        "Name": "Build a Parade",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-10"},
            {"ID": "Metal"},
            {"ID": "Pay amount", "Text": "-10"},
            {"ID": "Papyrus"},
            {"ID": "Arrow"},
            {"ID": "Place tile", "Text": "15"},
            {"ID": "Activate common card", "Text": "15"},
        ],
        "Text": "Pay 10 Metal and 10 Papyrus. Place a Parade tile and activate the Parade boon.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Place tile"}],
    },
    {
        "Name": "Build a Parade",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-14"},
            {"ID": "Metal"},
            {"ID": "Pay amount", "Text": "-6"},
            {"ID": "Papyrus"},
            {"ID": "Arrow"},
            {"ID": "Place tile", "Text": "15"},
            {"ID": "Activate common card", "Text": "15"},
        ],
        "Text": "Pay 14 Metal and 6 Papyrus. Place a Parade tile and activate the Parade boon.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Place tile"}],
    },

    // 10% draw Opportunity cards
    {
        "Name": "Fortunate encounter",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Opportunity card"},
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Discard card"},
        ],
        "Text": "Pay 1 Influence. Draw 2 Opportunity cards, then discard 1 card from your hand.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Opportunity card"}],
    },
    {
        "Name": "Fortunate encounter",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Opportunity card"},
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Discard card"},
        ],
        "Text": "Pay 1 Influence. Draw 2 Opportunity cards, then discard 1 card from your hand.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Opportunity card"}],
    },
    {
        "Name": "Family acquaintance",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Opportunity card"},
        ],
        "Text": "Pay 2 Influence. Draw 2 Opportunity cards.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Opportunity card"}],
    },
    {
        "Name": "Family acquaintance",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2"},
            {"ID": "Opportunity card"},
        ],
        "Text": "Pay 2 Influence. Draw 2 Opportunity cards.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Opportunity card"}],
    },
    {
        "Name": "Networking",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+3"},
            {"ID": "Opportunity card"},
        ],
        "Text": "Pay 3 Influence. Draw 3 Opportunity cards.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Opportunity card"}],
    },
    {
        "Name": "Networking",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-3"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+3"},
            {"ID": "Opportunity card"},
        ],
        "Text": "Pay 3 Influence. Draw 3 Opportunity cards.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Opportunity card"}],
    },
    {
        "Name": "Festival preparations",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-5"},
            {"ID": "Grain"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+3"},
            {"ID": "Opportunity card"},
        ],
        "Text": "Pay 1 Influence and 5 Grain. Draw 3 Opportunity cards.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Opportunity card"}],
    },
    {
        "Name": "Festival preparations",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-5"},
            {"ID": "Wood"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+3"},
            {"ID": "Opportunity card"},
        ],
        "Text": "Pay 1 Influence and 5 Wood. Draw 3 Opportunity cards.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Opportunity card"}],
    },
    {
        "Name": "Pious reputation",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-8"},
            {"ID": "Metal"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+5"},
            {"ID": "Opportunity card"},
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Discard card"},
        ],
        "Text": "Pay 1 Influence and 8 Metal. Draw 5 Opportunity cards, then discard 2 cards from your hand.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Opportunity card"}],
    },
    {
        "Name": "Prestigious reputation",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-8"},
            {"ID": "Papyrus"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+5"},
            {"ID": "Opportunity card"},
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Discard card"},
        ],
        "Text": "Pay 1 Influence and 8 Papyrus. Draw 5 Opportunity cards, then discard 2 cards from your hand.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Opportunity card"}],
    },

    // 5% additional common, buy, sell
    {
        "Name": "Extra Common project",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-X"},
            {"ID": "Resource"},
            {"ID": "Arrow"},
            {"ID": "Place tile", "Text": "X"}
        ],
        "Text": "Pay 1 Influence. Build a Common project.",
        "End": "Return",
        "Benefit icon": [{"ID": "Place tile"}],
    },
    {
        "Name": "Extra Common project",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-X"},
            {"ID": "Resource"},
            {"ID": "Arrow"},
            {"ID": "Place tile", "Text": "X"}
        ],
        "Text": "Pay 1 Influence. Build a Common project.",
        "End": "Return",
        "Benefit icon": [{"ID": "Place tile"}],
    },
    {
        "Name": "Extra buy resources",
        "Type": "Starting",
        "Order": "Player",
        "Icons": [
            {"ID": "Market up"},
            {"ID": "Pay amount", "Text": "-X"},
            {"ID": "Aureus"},
            {"ID": "Multi arrow"},
            {"ID": "Gain amount", "Text": "+5"},
            {"ID": "Resource"},
        ],
        "Text": "Increase the price marker of any resource in the Market by one level. Pay the new price in Aureus and gain 5 of that resource.\rRepeat as many times as you want for the same resource.",
        "End": "Return",
        "Benefit icon": [{"ID": "Resource"}],
    },
    {
        "Name": "Extra buy resources",
        "Type": "Starting",
        "Order": "Player",
        "Icons": [
            {"ID": "Market up"},
            {"ID": "Pay amount", "Text": "-X"},
            {"ID": "Aureus"},
            {"ID": "Multi arrow"},
            {"ID": "Gain amount", "Text": "+5"},
            {"ID": "Resource"},
        ],
        "Text": "Increase the price marker of any resource in the Market by one level. Pay the new price in Aureus and gain 5 of that resource.\rRepeat as many times as you want for the same resource.",
        "End": "Return",
        "Benefit icon": [{"ID": "Resource"}],
    },
    {
        "Name": "Extra sell resources",
        "Type": "Starting",
        "Order": "Player",
        "Icons": [
            {"ID": "Market down"},
            {"ID": "Pay amount", "Text": "-5"},
            {"ID": "Resource"},
            {"ID": "Multi arrow"},
            {"ID": "Gain amount", "Text": "+X"},
            {"ID": "Aureus"},
        ],
        "Text": "Decrease the price marker of any resource in the Market by one level. Pay 5 of that resource and gain the new price in Aureus.\rRepeat as many times as you want for the same resource.",
        "End": "Return",
        "Benefit icon": [{"ID": "Aureus"}],
    },

    // 5% special
    {
        "Name": "Favorable purchasing contract",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-X"},
            {"ID": "Aureus"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+6"},
            {"ID": "Resource"},
        ],
        "Text": "Pick any resource. Pay its current market price in Aurues and gain 6 of that resource.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Resource"}],
    },
    {
        "Name": "Villa",
        "Type": "Opportunity",
        "Order": "Player",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Pay amount", "Text": "-4"},
            {"ID": "Grain"},
            {"ID": "Arrow"},
            {"ID": "Place tile", "Text": "H1"},
        ],
        "Text": "Pay 1 Influence and 4 Grain. Place a Domas tile (1) on any space along the edge of the city.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Place tile"}],
    },
    {
        "Name": "Meditation and focus",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-X"},
            {"ID": "Discard card"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2X"},
            {"ID": "Influence"},
        ],
        "Text": "Discard any number of cards from your hand. Gain 2 Influence for each discarded card.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Influence"}],
    },
    {
        "Name": "Market manipulation",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Market up"},
            {"ID": "Market down"},
        ],
        "Text": "Pay 1 Influence. In the Market, increase a resource's price marker one level, and decrease a different resource's price marker one level.",
        "End": "Remove",
        "Benefit icon": [{"ID": "Market up"}],
    },
    {
        "Name": "Foresight",
        "Type": "Opportunity",
        "Order": "Immediate",
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+X"},
            {"ID": "Aureus"},
        ],
        "Text": "Pay 1 Influence. Gain 1 Aureus for each card in your hand (not including this one).",
        "End": "Remove",
        "Benefit icon": [{"ID": "Aureus"}],
    },
];

var  cardInfo = [];

var colors = [
    "Red",
    "Blue",
    "Green",
    "Purple",
    "Orange",
    "Cyan",
]

for (var i = 0; i < colors.length; i++) {
    for (var j = 0; j < startingCardInfo.length; j++) {
        var card = copyObj(startingCardInfo[j]);
        card["Type"] = "Starting";
        card["Player"] = colors[i];
        cardInfo.push(card);
    }
}

function copyObj(input) {
    var output = {};
    for (key in input) {
        output[key] = input[key];
    }
    return output;
}

var compass = [
    "N",
    "S",
    "W",
    "E",
];
var ci = 0;

for (var i = 0; i < opportunityCardInfo.length; i++) {
    opportunityCardInfo[i]["Compass"] = compass[ci];
    ci++;
    ci = ci % 4;
    opportunityCardInfo[i]["Type"] = "Opportunity";
    cardInfo.push(opportunityCardInfo[i])
}