var cardsShared = [
    {
        "Name": "Domas",
        "Caption": "Common",
        "Image": "Family",
        "Icons": [
            {"ID": "Tile owned", "Text": "D", "Optional": ["Home"]},
            {"ID": "Arrow"},
            {"ID": "VP", "Text": "1"},
        ],
        "Boon": "Every owned Domas: +1 VP.",
    },
    {
        "Name": "Shops",
        "Caption": "Common",
        "Image": "Family",
        "Icons": [
            {"ID": "Tile owned", "Text": "S", "Optional": ["Shop"]},
            {"ID": "Tile adjacent", "Text": "T", "Optional": ["Temple"]},
            {"ID": "Arrow"},
            {"ID": "VP", "Text": "3"},
        ],
        "Boon": "Every owned Shop adjacent to at least 1 Temple: +3 VP.",
    },
    {
        "Name": "Temples",
        "Caption": "Common",
        "Tile type": "Religion",
        "Image": "Family",
        "Icons": [
            {"ID": "Tile owned", "Text": "T", "Optional": ["Temple"]},
            {"ID": "Tile adjacent", "Text": "H", "Optional": ["Home"]},
            {"ID": "Arrow"},
            {"ID": "VP", "Text": "2X"},
        ],
        "Boon": "Every owned Temple: +2 VP for each adjacent Home.",
    },
    {
        "Name": "Libraries",
        "Caption": "Common",
        "Image": "Family",
        "Icons": [
            {"ID": "Tile owned", "Text": "L", "Optional": ["Civic"]},
            {"ID": "Tile owned", "Text": "L", "Optional": ["Civic"]},
            {"ID": "Tile owned", "Text": "L", "Optional": ["Civic"]},
            {"ID": "Arrow"},
            {"ID": "VP", "Text": "6"},
        ],
        "Boon": "Whoever owns the most Libraries: +6 VP.\rSplit the points (rounded down) in case of a tie.",
    },
    {
        "Name": "Amphitheatres",
        "Caption": "Special",
        "Image": "Building",
        "Icons": [
            {"ID": "Tile owned", "Text": "A"},
            {"ID": "Tile negative", "Text": "S", "Optional": ["Shop"]},
            {"ID": "Arrow"},
            {"ID": "VP", "Text": "6-2X"},
        ],
        "Boon": "Every owned Amphitheatre: +6 VP -2VP for each adjacent Shop. (Minimum 0 VP)",
    },
    {
        "Name": "Oracles",
        "Caption": "Special",
        "Tile type": "Religion",
        "Image": "Building",
        "Icons": [
            {"ID": "Tile owned", "Text": "O", "Optional": ["Temple"]},
            {"ID": "Tile adjacent", "Text": "T", "Optional": ["Temple"]},
            {"ID": "Arrow"},
            {"ID": "VP", "Text": "4X"},
        ],
        "Boon": "Every owned Oracle: +4VP for each adjacent Temple.",
    },
    {
        "Name": "Barracks",
        "Caption": "Special",
        "Tile type": "Military",
        "Image": "Warriors",
        "Icons": [
            {"ID": "Tile owned", "Text": "B", "Optional": ["Military"]},
            {"ID": "Tile owned", "Optional": ["Military"]},
            {"ID": "Arrow"},
            {"ID": "VP", "Text": "2X"},
        ],
        "Boon": "Every owned Barracks: +2 VP for each owned Military building (including itself).",
    },
    {
        "Name": "Parades",
        "Caption": "Special",
        "Tile type": "Military",
        "Image": "Warriors",
        "Icons": [
            {"ID": "Tile owned", "Text": "P", "Optional": ["Military"]},
            {"ID": "Arrow"},
            {"ID": "VP", "Text": "5"},
        ],
        "Boon": "Every owned Parade: +5 VP.",
    },
]