var cardsShared = [
    {
        "Name": "Domus",
        "Caption": "Common",
        "Image": "Family",
        "Icons": [
            {"ID": "Tile owned", "Text": "D", "Optional": ["Home"]},
            {"ID": "Tile adjacent", "Text": "S", "Optional": ["Shop"]},
            {"ID": "Slash"},
            {"ID": "Tile owned", "Text": "D", "Optional": ["Home"]},
            {"ID": "Tile adjacent", "Text": "L", "Optional": ["Civic"]},
            {"ID": "Arrow"},
            {"ID": "VP", "Text": "2"},
        ],
        "Boon": "Every owned Domus adjacent to at least 1 Shop or Library: 2 VP",
    },
    {
        "Name": "Shops",
        "Caption": "Common",
        "Image": "Family",
        "Icons": [
            {"ID": "Tile owned", "Text": "S", "Optional": ["Shop"]},
            {"ID": "Tile adjacent", "Text": "T", "Optional": ["Temple"]},
            {"ID": "Arrow"},
            {"ID": "VP", "Text": "2"},
        ],
        "Boon": "Every owned Shop adjacent to at least 1 Temple: 2 VP",
    },
    {
        "Name": "Temples",
        "Caption": "Common",
        "Image": "Family",
        "Icons": [
            {"ID": "Tile owned", "Text": "T", "Optional": ["Temple"]},
            {"ID": "Tile adjacent", "Text": "D", "Optional": ["Home"]},
            {"ID": "Arrow"},
            {"ID": "Multi VP", "Text": "1", "Optional": ["Hexes", "Home"]},
        ],
        "Boon": "Every owned Temple:\r1 VP for EACH adjacent Domus",
    },
    {
        "Name": "Libraries",
        "Caption": "Common",
        "Image": "Family",
        "Icons": [
            {"ID": "Gain amount", "Text": "Most"},
            {"ID": "Tile owned", "Text": "L", "Optional": ["Civic"]},
            {"ID": "Arrow"},
            {"ID": "VP", "Text": "7"},
        ],
        "Boon": "Whoever owns the most Libraries: 7 VP\rSplit the points (rounded down) in case of a tie",
    },
    {
        "Name": "Amphitheatres",
        "Caption": "Special",
        "Image": "Building",
        "Icons": [
            {"ID": "Tile owned", "Text": "A"},
            {"ID": "Tile adjacent", "Text": "S", "Optional": ["Shop"]},
            {"ID": "Arrow"},
            {"ID": "Multi VP", "Text": "2", "Optional": ["Hexes", "Shop"]},
        ],
        "Boon": "Every owned Amphitheatre:\r2 VP for EACH adjacent Shop",
    },
    {
        "Name": "Oracles",
        "Caption": "Special",
        "Image": "Building",
        "Icons": [
            {"ID": "Tile owned", "Text": "O", "Optional": ["Temple"]},
            {"ID": "Tile adjacent", "Text": "R", "Optional": ["Temple"]},
            {"ID": "Arrow"},
            {"ID": "Multi VP", "Text": "3", "Optional": ["Hexes", "Temple"]},
        ],
        "Boon": "Every owned Oracle:\r3 VP for EACH adjacent Temple",
    },
    {
        "Name": "Barracks",
        "Caption": "Special",
        "Tile type": "Military",
        "Image": "Warriors",
        "Icons": [
            {"ID": "Tile owned", "Text": "B", "Optional": ["Military"]},
            {"ID": "Tile owned", "Optional": ["Military"]},
            {"ID": "Arrow"},
            {"ID": "Multi VP", "Text": "1", "Optional": ["Hexes", "Military"]},
        ],
        "Boon": "Every owned Barracks: 1 VP for EACH owned Military building (including itself; adjacency not required)",
    },
    {
        "Name": "Parades",
        "Caption": "Special",
        "Tile type": "Military",
        "Image": "Warriors",
        "Icons": [
            {"ID": "Tile owned", "Text": "P", "Optional": ["Military"]},
            {"ID": "Arrow"},
            {"ID": "VP", "Text": "4"},
        ],
        "Boon": "Every owned Parade: 4 VP",
    },
]