var cardsShared = [
    {
        "Name": "Domus",
        "Caption": "Common",
        "Image": "Family",
        "Icons": [
            {"ID": "Tile owned", "Text": "D", "Optional": ["Home"]},
            {"ID": "Tile adjacent", "Text": "S", "Optional": ["Shop"]},
            {"ID": "Neutral amount", "Text": "/"},
            {"ID": "Tile owned", "Text": "D", "Optional": ["Home"]},
            {"ID": "Tile adjacent", "Text": "L", "Optional": ["Civic"]},
            {"ID": "Arrow"},
            {"ID": "VP", "Text": "1"},
        ],
        "Boon": "Every owned Domus adjacent to at least 1 Shop or Library: +1 VP.",
    },
    {
        "Name": "Shops",
        "Caption": "Common",
        "Image": "Family",
        "Icons": [
            {"ID": "Tile owned", "Text": "S", "Optional": ["Shop"]},
            {"ID": "Tile adjacent", "Text": "R", "Optional": ["Temple"]},
            {"ID": "Arrow"},
            {"ID": "VP", "Text": "2"},
        ],
        "Boon": "Every owned Shop adjacent to at least 1 Religion building: +2 VP.",
    },
    {
        "Name": "Temples",
        "Caption": "Common",
        "Tile type": "Religion",
        "Image": "Family",
        "Icons": [
            {"ID": "Tile owned", "Text": "T", "Optional": ["Temple"]},
            {"ID": "Tile adjacent", "Text": "D", "Optional": ["Home"]},
            {"ID": "Arrow"},
            {"ID": "VP", "Text": "X"},
        ],
        "Boon": "Every owned Temple: +1 VP for each adjacent Domus.",
    },
    {
        "Name": "Libraries",
        "Caption": "Common",
        "Image": "Family",
        "Icons": [
            {"ID": "Gain amount", "Text": "Most"},
            {"ID": "Tile owned", "Text": "L", "Optional": ["Civic"]},
            {"ID": "Arrow"},
            {"ID": "VP", "Text": "7"},
        ],
        "Boon": "Whoever owns the most Libraries: +7 VP.\rSplit the points (rounded down) in case of a tie.",
    },
    {
        "Name": "Amphitheatres",
        "Caption": "Special",
        "Image": "Building",
        "Icons": [
            {"ID": "Tile owned", "Text": "A"},
            {"ID": "Tile negative", "Text": "S", "Optional": ["Shop"]},
            {"ID": "Arrow"},
            {"ID": "VP", "Text": "5-2X"},
        ],
        "Boon": "Every owned Amphitheatre: +5 VP -2VP for each adjacent Shop (Minimum 0 VP).",
    },
    {
        "Name": "Oracles",
        "Caption": "Special",
        "Tile type": "Religion",
        "Image": "Building",
        "Icons": [
            {"ID": "Tile owned", "Text": "O", "Optional": ["Temple"]},
            {"ID": "Tile adjacent", "Text": "R", "Optional": ["Temple"]},
            {"ID": "Arrow"},
            {"ID": "VP", "Text": "3X"},
        ],
        "Boon": "Every owned Oracle: +3VP for each adjacent Religion building.",
    },
    {
        "Name": "Barracks",
        "Caption": "Special",
        "Tile type": "Military",
        "Image": "Warriors",
        "Icons": [
            {"ID": "Tile owned", "Text": "B", "Optional": ["Military"]},
            {"ID": "Tile owned", "Optional": ["Military"]},
            {"ID": "Arrow"},
            {"ID": "VP", "Text": "X"},
        ],
        "Boon": "Every owned Barracks: +1 VP for each owned Military building (including itself).",
    },
    {
        "Name": "Parades",
        "Caption": "Special",
        "Tile type": "Military",
        "Image": "Warriors",
        "Icons": [
            {"ID": "Tile owned", "Text": "P", "Optional": ["Military"]},
            {"ID": "Arrow"},
            {"ID": "VP", "Text": "4"},
        ],
        "Boon": "Every owned Parade: +4 VP.",
    },
]