var cardsFamily = [
    {
        "Name": "Remus family",
        "Type": "Family",
        "Family type": "Beginner",
        "Image": "Family",
        "Starting resources": {
            "Influence": 5,
            "Aureus": 3,
            "Grain": 3,
            "Wood": 1,
            "Metal": 1,
            "Papyrus": 1,
        },
        "Icons": [
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "2"},
            {"ID": "Opportunity"},
        ],
        "Text": "Gain 2 Opportunities.",
        "Benefit icon": [{"ID": "Opportunity"}],
        "End": "Discard",
    },
    {
        "Name": "Sideris family",
        "Type": "Family",
        "Family type": "Beginner",
        "Image": "Family",
        "Starting resources": {
            "Influence": 4,
            "Aureus": 6,
            "Grain": 3,
            "Wood": 1,
            "Metal": "0",
            "Papyrus": "0",
        },
        "Icons": [
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "2"},
            {"ID": "Opportunity"},
        ],
        "Text": "Gain 2 Opportunities.",
        "Benefit icon": [{"ID": "Opportunity"}],
        "End": "Discard",
    },
    {
        "Name": "Florentina family",
        "Type": "Family",
        "Family type": "Beginner",
        "Image": "Family",
        "Starting resources": {
            "Influence": 5,
            "Aureus": 3,
            "Grain": 1,
            "Wood": 3,
            "Metal": 1,
            "Papyrus": 1,
        },
        "Icons": [
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "2"},
            {"ID": "Opportunity"},
        ],
        "Text": "Gain 2 Opportunities.",
        "Benefit icon": [{"ID": "Opportunity"}],
        "End": "Discard",
    },
    {
        "Name": "Beatirx family",
        "Type": "Family",
        "Family type": "Beginner",
        "Image": "Family",
        "Starting resources": {
            "Influence": 4,
            "Aureus": 6,
            "Grain": 1,
            "Wood": 3,
            "Metal": "0",
            "Papyrus": "0",
        },
        "Icons": [
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "2"},
            {"ID": "Opportunity"},
        ],
        "Text": "Gain 2 Opportunities.",
        "Benefit icon": [{"ID": "Opportunity"}],
        "End": "Discard",
    },
    {
        "Name": "Leos family",
        "Type": "Family",
        "Family type": "Beginner",
        "Image": "Family",
        "Starting resources": {
            "Influence": 5,
            "Aureus": 3,
            "Grain": 1,
            "Wood": 1,
            "Metal": 3,
            "Papyrus": 1,
        },
        "Icons": [
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "2"},
            {"ID": "Opportunity"},
        ],
        "Text": "Gain 2 Opportunities.",
        "Benefit icon": [{"ID": "Opportunity"}],
        "End": "Discard",
    },
    {
        "Name": "Baros family",
        "Type": "Family",
        "Family type": "Beginner",
        "Image": "Family",
        "Starting resources": {
            "Influence": 4,
            "Aureus": 6,
            "Grain": "0",
            "Wood": 1,
            "Metal": 3,
            "Papyrus": "0",
        },
        "Icons": [
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "2"},
            {"ID": "Opportunity"},
        ],
        "Text": "Gain 2 Opportunities.",
        "Benefit icon": [{"ID": "Opportunity"}],
        "End": "Discard",
    },
    {
        "Name": "Leventis family",
        "Type": "Family",
        "Family type": "Advanced",
        "Image": "Family",
        "Starting resources": {
            "Influence": 3,
            "Aureus": 6,
            "Grain": "0",
            "Wood": "0",
            "Metal": 2,
            "Papyrus": "0",
        },
        "Order": "Immediate",
        "Icons": [
            {"ID": "Arrow"},
            {"ID": "Swap power and wealth"},
        ],
        "Text": "Swap your Power and Wealth markers",
        "End": "Return",
        "Benefit icon": [{"ID": "Swap power and wealth"}],
    },
    {
        "Name": "Piuso family",
        "Type": "Family",
        "Family type": "Advanced",
        "Image": "Family",
        "Starting resources": {
            "Influence": 5,
            "Aureus": 3,
            "Grain": 1,
            "Wood": 2,
            "Metal": "0",
            "Papyrus": "0",
        },
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Pay amount", "Text": "1/2"},
            {"ID": "Metal"},
            {"ID": "Place tile", "Text": "T", "Optional": ["Temple"]},
        ],
        "Text": "Pay 1 Influence. Build a Temple for half its listed Common cost (rounded up).",
        "End": "Return",
        "Benefit icon": [{"ID": "Place tile", "Text": "T", "Optional": ["Temple"]}],
    },
    {
        "Name": "Nomano family",
        "Type": "Family",
        "Family type": "Advanced",
        "Image": "Family",
        "Starting resources": {
            "Influence": 4,
            "Aureus": 3,
            "Grain": 2,
            "Wood": "0",
            "Metal": "0",
            "Papyrus": 2,
        },
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+1"},
            {"ID": "Market up"},
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Market down"},
        ],
        "Text": "Pay 1 Influence. Raise the price of any resource in the Market 1 level and lower the price of any other resource 1 level.",
        "End": "Return",
        "Benefit icon": [{"ID": "Market manipulation"}],
    },
    {
        "Name": "Decimus family",
        "Type": "Family",
        "Family type": "Advanced",
        "Image": "Family",
        "Starting resources": {
            "Influence": 3,
            "Aureus": 5,
            "Grain": "0",
            "Wood": 1,
            "Metal": 3,
            "Papyrus": "0",
        },
        "Icons": [
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+2X"},
            {"ID": "Tile adjacent", "Optional": ["Shop"]},
            {"ID": "Aureus"},
        ],
        "Text": "Gain 2 Auerus for each Shop in the city (owned by anyone).",
        "End": "Discard",
        "Benefit icon": [{"ID": "Aureus"}],
    },
    {
        "Name": "Amata family",
        "Type": "Family",
        "Family type": "Advanced",
        "Image": "Family",
        "Starting resources": {
            "Influence": 5,
            "Aureus": 4,
            "Grain": 3,
            "Wood": "0",
            "Metal": "0",
            "Papyrus": "0",
        },
        "Icons": [
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "+X"},
            {"ID": "Tile adjacent", "Optional": ["Home"]},
            {"ID": "Aureus"},
        ],
        "Text": "Gain 1 Auerus for each Home in the city (owned by anyone).",
        "End": "Discard",
        "Benefit icon": [{"ID": "Aureus"}],
    },
    {
        "Name": "Corvinus family",
        "Type": "Family",
        "Family type": "Advanced",
        "Image": "Family",
        "Starting resources": {
            "Influence": 3,
            "Aureus": 6,
            "Grain": 2,
            "Wood": "0",
            "Metal": "0",
            "Papyrus": "0",
        },
        "Icons": [
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Wood"},
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Metal"},
            {"ID": "Pay amount", "Text": "-2"},
            {"ID": "Papyrus"},
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "3"},
            {"ID": "Influence"},
        ],
        "Text": "Pay 2 Wood, 2 Metal, and 2 Papyrus. Gain 3 Influence.",
        "End": "Keep",
        "Trigger icon": [{"ID": "Opportunity"}],
        "Trigger text": "When the card above gains an Opportunity, gain 1 Influence.",
        "Benefit icon": [{"ID": "Influence"}],
    },
    
    {
        "Type": "Last generation"
    }
]