var cardsFamily = [
    {
        "Name": "Remus family",
        "Type": "Family",
        "Family type": "Beginner",
        "Image": "Family",
        "Starting resources": {
            "Influence": 5,
            "Aureus": 3,
            "Grain": 3,
            "Wood": 1,
            "Metal": 1,
            "Papyrus": 1,
        },
        "Icons": [
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "2"},
            {"ID": "Opportunity card"},
        ],
        "Text": "Gain 2 Opportunities.",
        "Benefit icon": [{"ID": "Opportunity card"}],
        "End": "Discard",
    },
    {
        "Name": "Sideris family",
        "Type": "Family",
        "Family type": "Beginner",
        "Image": "Family",
        "Starting resources": {
            "Influence": 4,
            "Aureus": 6,
            "Grain": 3,
            "Wood": 1,
            "Metal": "0",
            "Papyrus": "0",
        },
        "Icons": [
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "2"},
            {"ID": "Opportunity card"},
        ],
        "Text": "Gain 2 Opportunities.",
        "Benefit icon": [{"ID": "Opportunity card"}],
        "End": "Discard",
    },
    {
        "Name": "Florentina family",
        "Type": "Family",
        "Family type": "Beginner",
        "Image": "Family",
        "Starting resources": {
            "Influence": 5,
            "Aureus": 3,
            "Grain": 1,
            "Wood": 3,
            "Metal": 1,
            "Papyrus": 1,
        },
        "Icons": [
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "2"},
            {"ID": "Opportunity card"},
        ],
        "Text": "Gain 2 Opportunities.",
        "Benefit icon": [{"ID": "Opportunity card"}],
        "End": "Discard",
    },
    {
        "Name": "Beatirx family",
        "Type": "Family",
        "Family type": "Beginner",
        "Image": "Family",
        "Starting resources": {
            "Influence": 4,
            "Aureus": 6,
            "Grain": 1,
            "Wood": 3,
            "Metal": "0",
            "Papyrus": "0",
        },
        "Icons": [
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "2"},
            {"ID": "Opportunity card"},
        ],
        "Text": "Gain 2 Opportunities.",
        "Benefit icon": [{"ID": "Opportunity card"}],
        "End": "Discard",
    },
    {
        "Name": "Leos family",
        "Type": "Family",
        "Family type": "Beginner",
        "Image": "Family",
        "Starting resources": {
            "Influence": 5,
            "Aureus": 3,
            "Grain": 1,
            "Wood": 1,
            "Metal": 3,
            "Papyrus": 1,
        },
        "Icons": [
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "2"},
            {"ID": "Opportunity card"},
        ],
        "Text": "Gain 2 Opportunities.",
        "Benefit icon": [{"ID": "Opportunity card"}],
        "End": "Discard",
    },
    {
        "Name": "Baros family",
        "Type": "Family",
        "Family type": "Beginner",
        "Image": "Family",
        "Starting resources": {
            "Influence": 4,
            "Aureus": 6,
            "Grain": "0",
            "Wood": 1,
            "Metal": 3,
            "Papyrus": "0",
        },
        "Icons": [
            {"ID": "Arrow"},
            {"ID": "Gain amount", "Text": "2"},
            {"ID": "Opportunity card"},
        ],
        "Text": "Gain 2 Opportunities.",
        "Benefit icon": [{"ID": "Opportunity card"}],
        "End": "Discard",
    },
    {
        "Name": "Leventis family",
        "Type": "Family",
        "Family type": "Advanced",
        "Image": "Family",
        "Starting resources": {
            "Influence": 3,
            "Aureus": 6,
            "Grain": "0",
            "Wood": "0",
            "Metal": 2,
            "Papyrus": "0",
        },
        "Order": "Immediate",
        "Icons": [
            {"ID": "Arrow"},
            {"ID": "Swap power and wealth"},
        ],
        "Text": "Swap your Power and Wealth markers",
        "End": "Return",
        "Benefit icon": [{"ID": "Swap power and wealth"}],
    },
    {
        "Name": "Piuso family",
        "Type": "Family",
        "Family type": "Advanced",
        "Image": "Family",
        "Starting resources": {
            "Influence": 5,
            "Aureus": 3,
            "Grain": 1,
            "Wood": 2,
            "Metal": "0",
            "Papyrus": "0",
        },
        "Icons": [
            {"ID": "Pay amount", "Text": "-1"},
            {"ID": "Influence"},
            {"ID": "Arrow"},
            {"ID": "Pay amount", "Text": "1/2"},
            {"ID": "Metal"},
            {"ID": "Place tile", "Text": "T", "Optional": ["Temple"]},
        ],
        "Text": "Pay 1 Influence. Build a Temple for half its listed Common cost (rounded up).",
        "End": "Return",
        "Benefit icon": [{"ID": "Place tile", "Text": "T", "Optional": ["Temple"]}],
    },
]