var cardsFamily = [
    {
        "Name": "Remus family",
        "Type": "Family",
        "Family type": "Beginner",
        "Image": "Family",
        "Starting resources": {
            "Power": 5,
            "Wealth": 3,
            "Grain": 5,
            "Wood": 1,
            "Iron": 2,
            "Stone": 2,
        },
        "Icons": [
            { "ID": "Arrow" },
            { "ID": "Gain amount", "Text": "2" },
            { "ID": "Opportunity" },
        ],
        "Text": "Gain 2 Opportunities.",
        "After": "Once",
    },
    {
        "Name": "Sideris family",
        "Type": "Family",
        "Family type": "Beginner",
        "Image": "Family",
        "Starting resources": {
            "Power": 3,
            "Wealth": 5,
            "Grain": 2,
            "Wood": 5,
            "Iron": 2,
            "Stone": 1,
        },
        "Icons": [
            { "ID": "Arrow" },
            { "ID": "Gain amount", "Text": "2" },
            { "ID": "Opportunity" },
        ],
        "Text": "Gain 2 Opportunities.",
        "After": "Once",
    },
    {
        "Name": "Florentina family",
        "Type": "Family",
        "Family type": "Beginner",
        "Image": "Family",
        "Starting resources": {
            "Power": 3,
            "Wealth": 4,
            "Grain": 3,
            "Wood": 3,
            "Iron": 5,
            "Stone": 2,
        },
        "Icons": [
            { "ID": "Arrow" },
            { "ID": "Gain amount", "Text": "2" },
            { "ID": "Opportunity" },
        ],
        "Text": "Gain 2 Opportunities.",
        "After": "Once",
    },
    {
        "Name": "Beatrix family",
        "Type": "Family",
        "Family type": "Beginner",
        "Image": "Family",
        "Starting resources": {
            "Power": 4,
            "Wealth": 3,
            "Grain": 3,
            "Wood": 3,
            "Iron": 2,
            "Stone": 5,
        },
        "Icons": [
            { "ID": "Arrow" },
            { "ID": "Gain amount", "Text": "2" },
            { "ID": "Opportunity" },
        ],
        "Text": "Gain 2 Opportunities.",
        "After": "Once",
    },
    {
        "Name": "Leos family",
        "Type": "Family",
        "Family type": "Beginner",
        "Image": "Family",
        "Starting resources": {
            "Power": 3,
            "Wealth": 4,
            "Grain": 4,
            "Wood": 4,
            "Iron": 1,
            "Stone": 1,
        },
        "Icons": [
            { "ID": "Pay amount", "Text": "-2" },
            { "ID": "Grain" },
            { "ID": "Arrow" },
            { "ID": "Place tile", "Text": "F", "Optional": "Industry" },
        ],
        "Text": "Pay 2 Grain. Build a Farm.",
        "After": "Once",
    },
    {
        "Name": "Baros family",
        "Type": "Family",
        "Family type": "Beginner",
        "Image": "Family",
        "Starting resources": {
            "Power": 4,
            "Wealth": 3,
            "Grain": 4,
            "Wood": 4,
            "Iron": 1,
            "Stone": 1,
        },
        "Icons": [
            { "ID": "Pay amount", "Text": "-2" },
            { "ID": "Wood" },
            { "ID": "Arrow" },
            { "ID": "Place tile", "Text": "L", "Optional": "Industry" },
        ],
        "Text": "Pay 2 Wood. Build a Lumber mill.",
        "After": "Once",
    },
    {
        "Name": "Leventis family",
        "Type": "Family",
        "Family type": "Beginner",
        "Image": "Family",
        "Starting resources": {
            "Power": 3,
            "Wealth": 4,
            "Grain": 1,
            "Wood": 1,
            "Iron": 4,
            "Stone": 4,
        },
        "Icons": [
            { "ID": "Pay amount", "Text": "-2" },
            { "ID": "Iron" },
            { "ID": "Arrow" },
            { "ID": "Place tile", "Text": "M", "Optional": "Industry" },
        ],
        "Text": "Pay 2 Iron. Build a Mine.",
        "After": "Once",
    },
    {
        "Name": "Piuso family",
        "Type": "Family",
        "Family type": "Beginner",
        "Image": "Family",
        "Starting resources": {
            "Power": 4,
            "Wealth": 3,
            "Grain": 1,
            "Wood": 1,
            "Iron": 4,
            "Stone": 4,
        },
        "Icons": [
            { "ID": "Pay amount", "Text": "-2" },
            { "ID": "Stone" },
            { "ID": "Arrow" },
            { "ID": "Place tile", "Text": "Q", "Optional": "Industry" },
        ],
        "Text": "Pay 2 Stone. Build a Quarry.",
        "After": "Once",
    },
    {
        "Name": "Scipio family",
        "Type": "Family",
        "Family type": "Beginner",
        "Image": "Family",
        "Starting resources": {
            "Power": 3,
            "Wealth": 4,
            "Grain": 4,
            "Wood": 1,
            "Iron": 1,
            "Stone": 4,
        },
        "Icons": [
            { "ID": "Pay amount", "Text": "-3" },
            { "ID": "Grain" },
            { "ID": "Arrow" },
            { "ID": "Place tile", "Text": "G", "Optional": "Aux" },
        ],
        "Text": "Pay 3 Grain. Build a Green field.",
        "After": "Once",
    },
    {
        "Name": "Sulla family",
        "Type": "Family",
        "Family type": "Beginner",
        "Image": "Family",
        "Starting resources": {
            "Power": 4,
            "Wealth": 3,
            "Grain": 1,
            "Wood": 4,
            "Iron": 4,
            "Stone": 1,
        },
        "Icons": [
            { "ID": "Pay amount", "Text": "-3" },
            { "ID": "Wood" },
            { "ID": "Arrow" },
            { "ID": "Place tile", "Text": "G", "Optional": "Aux" },
        ],
        "Text": "Pay 3 Wood. Build a Green field.",
        "After": "Once",
    },
    {
        "Name": "Octavius family",
        "Type": "Family",
        "Family type": "Beginner",
        "Image": "Family",
        "Starting resources": {
            "Power": 3,
            "Wealth": 4,
            "Grain": 4,
            "Wood": 1,
            "Iron": 1,
            "Stone": 4,
        },
        "Icons": [
            { "ID": "Pay amount", "Text": "-3" },
            { "ID": "Stone" },
            { "ID": "Arrow" },
            { "ID": "Place tile", "Text": "R", "Optional": "Aux" },
        ],
        "Text": "Pay 3 Stone. Build a Rocky field.",
        "After": "Once",
    },
    {
        "Name": "Gracchus family",
        "Type": "Family",
        "Family type": "Beginner",
        "Image": "Family",
        "Starting resources": {
            "Power": 4,
            "Wealth": 3,
            "Grain": 1,
            "Wood": 4,
            "Iron": 4,
            "Stone": 1,
        },
        "Icons": [
            { "ID": "Pay amount", "Text": "-3" },
            { "ID": "Iron" },
            { "ID": "Arrow" },
            { "ID": "Place tile", "Text": "R", "Optional": "Aux" },
        ],
        "Text": "Pay 3 Iron. Build a Rocky field.",
        "After": "Once",
    },

    // Standard
    {
        "Name": "Nomano family",
        "Type": "Family",
        "Family type": "Standard",
        "Image": "Family",
        "Starting resources": {
            "Power": 4,
            "Wealth": 2,
            "Grain": 4,
            "Wood": "0",
            "Iron": "0",
            "Stone": 4,
        },
        "Icons": [
            { "ID": "Arrow" },
            { "ID": "Gain amount", "Text": "-2 - +2" },
            { "ID": "Market manipulation" },
        ],
        "Text": "Raise or lower the price of any resource in the Market by up to 2 levels.",
        "After": "Dynasty",
    },
    {
        "Name": "Giovichi family",
        "Type": "Family",
        "Family type": "Standard",
        "Image": "Family",
        "Starting resources": {
            "Power": 2,
            "Wealth": 4,
            "Grain": 5,
            "Wood": "0",
            "Iron": 4,
            "Stone": "0",
        },
        "Icons": [
            { "ID": "Pay amount", "Text": "-2" },
            { "ID": "Iron" },
            { "ID": "Arrow" },
            { "ID": "Rearrange opportunities" },
        ],
        "Text": "Pay 2 Iron. Rearrange the 6 face-up Opportunity cards to any new ordering.",
        "After": "Dynasty",
    },
    {
        "Name": "Harmaxious family",
        "Type": "Family",
        "Family type": "Standard",
        "Image": "Family",
        "Starting resources": {
            "Power": 1,
            "Wealth": 4,
            "Grain": "0",
            "Wood": 3,
            "Iron": "0",
            "Stone": 3,
        },
        "Icons": [
            { "ID": "Pay amount", "Text": "-2" },
            { "ID": "Grain" },
            { "ID": "Arrow" },
            { "ID": "Swap power and wealth" },
        ],
        "Text": "Pay 2 Grain. Swap your Wealth and Power tokens.",
        "After": "Dynasty",
    },
    {
        "Name": "Rathorea family",
        "Type": "Family",
        "Family type": "Standard",
        "Image": "Family",
        "Starting resources": {
            "Power": 4,
            "Wealth": 3,
            "Grain": 3,
            "Wood": "0",
            "Iron": "0",
            "Stone": 3,
        },
        "Icons": [
            { "ID": "Pay amount", "Text": "-3" },
            { "ID": "Resource" },
            { "ID": "Arrow" },
            { "ID": "Gain amount", "Text": "+3" },
            { "ID": "Resource" },
        ],
        "Text": "Pay 3 Grain, Wood, Iron, or Stone. Gain 3 Grain, Wood, Iron, or Stone (your choice).",
        "After": "Dynasty",
    },
    {
        "Name": "Aether family",
        "Type": "Family",
        "Family type": "Standard",
        "Image": "Family",
        "Starting resources": {
            "Power": 2,
            "Wealth": 4,
            "Grain": "0",
            "Wood": "0",
            "Iron": 5,
            "Stone": 4,
        },
        "Icons": [
            { "ID": "Reset industry tokens" },
            { "ID": "Arrow" },
            { "ID": "Gain amount", "Text": "+0/1/2" },
            { "ID": "Influence" },
        ],
        "Text": "Reset all flipped Industry tokens, gaining Silver as normal.\rIf you flipped 10-14 tokens, gain 1 Influence.\rIf you flipped 15+ tokens, gain 2 Influence.",
        "After": "Dynasty",
    },
    {
        "Name": "Cicero family",
        "Type": "Family",
        "Family type": "Standard",
        "Image": "Family",
        "Starting resources": {
            "Power": 3,
            "Wealth": 3,
            "Grain": "0",
            "Wood": 4,
            "Iron": "0",
            "Stone": 2,
        },
        "Icons": [
            { "ID": "Pay amount", "Text": "-2" },
            { "ID": "Wood" },
            { "ID": "Arrow" },
            { "ID": "Activate industry" },
        ],
        "Text": "Pay 2 Wood. Activate industry.",
        "After": "Dynasty",
    },
    {
        "Name": "Bastious family",
        "Type": "Family",
        "Family type": "Standard",
        "Image": "Family",
        "Starting resources": {
            "Power": 2,
            "Wealth": 4,
            "Grain": 2,
            "Wood": 5,
            "Iron": "0",
            "Stone": "0",
        },
        "Icons": [
            { "ID": "Pay amount", "Text": "-1" },
            { "ID": "Grain" },
            { "ID": "Pay amount", "Text": "-X" },
            { "ID": "Silver" },
            { "ID": "Arrow" },
            { "ID": "Gain amount", "Text": "+4" },
            { "ID": "Resource" },
        ],
        "Text": "Pay 1 Grain.\rPick any resource. Pay its current price in Silver, then gain 4 of that resource",
        "After": "Dynasty",
    },
    {
        "Name": "Amadeus family",
        "Type": "Family",
        "Family type": "Standard",
        "Image": "Family",
        "Starting resources": {
            "Power": 4,
            "Wealth": 2,
            "Grain": "0",
            "Wood": 5,
            "Iron": "0",
            "Stone": 4,
        },
        "Icons": [
            { "ID": "Pay amount", "Text": "-3" },
            { "ID": "Iron" },
            { "ID": "Arrow" },
            { "ID": "Gain amount", "Text": "+1" },
            { "ID": "Opportunity" },
        ],
        "Text": "Pay 3 Iron.\rGain an Opportunity.",
        "After": "Dynasty",
    },
    {
        "Name": "Orpheo family",
        "Type": "Family",
        "Family type": "Standard",
        "Image": "Family",
        "Starting resources": {
            "Power": 4,
            "Wealth": 3,
            "Grain": "0",
            "Wood": 5,
            "Iron": "0",
            "Stone": 6,
        },
        "Icons": [
            { "ID": "Arrow" },
            { "ID": "Place tile", "Optional": "Multi" },
        ],
        "Text": "Build a Common building for free, ignoring the cost on the tile.",
        "After": "Once",
    },
    {
        "Name": "Sotesco family",
        "Type": "Family",
        "Family type": "Standard",
        "Image": "Family",
        "Starting resources": {
            "Power": 3,
            "Wealth": 3,
            "Grain": 4,
            "Wood": "0",
            "Iron": "0",
            "Stone": 5,
        },
        "Icons": [
            { "ID": "Pay amount", "Text": "-3" },
            { "ID": "Stone" },
            { "ID": "Arrow" },
            { "ID": "Claim tile" },
        ],
        "Text": "Pay 3 Stone. Put one of your banners on any Common building in the city without a banner.",
        "After": "Dynasty",
    },
    {
        "Name": "Scipiones family",
        "Type": "Family",
        "Family type": "Standard",
        "Image": "Family",
        "Starting resources": {
            "Power": 3,
            "Wealth": 3,
            "Grain": "0",
            "Wood": 5,
            "Iron": 4,
            "Stone": "0",
        },
        "Icons": [
            { "ID": "Pay amount", "Text": "-2" },
            { "ID": "Grain" },
            { "ID": "Arrow" },
            { "ID": "Gain amount", "Text": "+3" },
            { "ID": "Silver" },
        ],
        "Text": "Pay 2 Grain. Gain 3 Silver.",
        "After": "Dynasty",
    },

    {
        "Name": "Decimus family",
        "Type": "Family",
        "Family type": "Standard",
        "Image": "Family",
        "Starting resources": {
            "Power": 2,
            "Wealth": 4,
            "Grain": "0",
            "Wood": "0",
            "Iron": 4,
            "Stone": 5,
        },
        "Icons": [
            { "ID": "Arrow" },
            { "ID": "Gain amount", "Text": "+1x" },
            { "ID": "Tile adjacent", "Text": "S", "Optional": ["Shop"] },
            { "ID": "Influence" },
        ],
        "Text": "Gain 1 Influence for each Shop in the city (owned by anyone).",
        "After": "Once",
    },
    {
        "Name": "Amata family",
        "Type": "Family",
        "Family type": "Standard",
        "Image": "Family",
        "Starting resources": {
            "Power": 4,
            "Wealth": 2,
            "Grain": 5,
            "Wood": 4,
            "Iron": "0",
            "Stone": "0",
        },
        "Icons": [
            { "ID": "Arrow" },
            { "ID": "Gain amount", "Text": "+1x" },
            { "ID": "Tile adjacent", "Text": "D", "Optional": ["Domas"] },
            { "ID": "Influence" },
        ],
        "Text": "Gain 1 Influence for each Domas in the city (owned by anyone).",
        "After": "Once",
    },
    {
        "Name": "Terea family",
        "Type": "Family",
        "Family type": "Standard",
        "Image": "Family",
        "Starting resources": {
            "Power": 2,
            "Wealth": 4,
            "Grain": "0",
            "Wood": 3,
            "Iron": 5,
            "Stone": 5,
        },
        "Icons": [
            { "ID": "Arrow" },
            { "ID": "Gain amount", "Text": "+1x" },
            { "ID": "Tile adjacent", "Text": "T", "Optional": ["Temple"] },
            { "ID": "Influence" },
        ],
        "Text": "Gain 1 Influence for each Temple in the city (owned by anyone).",
        "After": "Once",
    },
    {
        "Name": "Pheasis family",
        "Type": "Family",
        "Family type": "Standard",
        "Image": "Family",
        "Starting resources": {
            "Power": 2,
            "Wealth": 3,
            "Grain": 4,
            "Wood": 4,
            "Iron": "0",
            "Stone": "0",
        },
        "Icons": [
            { "ID": "Arrow" },
            { "ID": "Gain amount", "Text": "+1x" },
            { "ID": "Tile adjacent", "Text": "", "Optional": ["Industry"] },
            { "ID": "Influence" },
        ],
        "Text": "Gain 1 Influence for each Industry building in the city (owned by anyone).",
        "After": "Once",
    },
    {
        "Name": "Haxinus family",
        "Type": "Family",
        "Family type": "Standard",
        "Image": "Family",
        "Starting resources": {
            "Power": 4,
            "Wealth": 3,
            "Grain": "0",
            "Wood": "0",
            "Iron": 5,
            "Stone": 4,
        },
        "Icons": [
            { "ID": "Arrow" },
            { "ID": "Gain amount", "Text": "+1x" },
            { "ID": "Tile adjacent", "Text": "", "Optional": ["Military"] },
            { "ID": "Influence" },
        ],
        "Text": "Gain 1 Influence for each Military building in the city (owned by anyone).",
        "After": "Once",
    },

    {
        "Name": "Corvinus family",
        "Type": "Family",
        "Family type": "Standard",
        "Image": "Family",
        "Starting resources": {
            "Power": 3,
            "Wealth": 3,
            "Grain": 5,
            "Wood": "0",
            "Iron": "0",
            "Stone": 5,
        },
        "Icons": [
            { "ID": "Tile owned", "Text": "", "Optional": "Military" },
            { "ID": "Tile owned", "Text": "", "Optional": "Military" },
            { "ID": "Tile owned", "Text": "", "Optional": "Military" },
            { "ID": "Arrow" },
            { "ID": "Gain amount", "Text": "+2" },
            { "ID": "Power" },
        ],
        "Text": "To play this card, you must own 3 Military buildings.\rIncrease your Power by 2",
        "After": "Once",
    },
    {
        "Name": "Telcorus family",
        "Type": "Family",
        "Family type": "Standard",
        "Image": "Family",
        "Starting resources": {
            "Power": 3,
            "Wealth": 2,
            "Grain": 2,
            "Wood": 2,
            "Iron": 2,
            "Stone": 2,
        },
        "Icons": [
            { "ID": "Tile owned", "Text": "B", "Optional": "Bath" },
            { "ID": "Tile owned", "Text": "B", "Optional": "Bath" },
            { "ID": "Arrow" },
            { "ID": "Gain amount", "Text": "+2" },
            { "ID": "Wealth" },
        ],
        "Text": "To play this card, you must own 2 Baths.\rIncrease your Wealth by 2",
        "After": "Once",
    },
    {
        "Name": "Severan family",
        "Type": "Family",
        "Family type": "Standard",
        "Image": "Family",
        "Starting resources": {
            "Power": 3,
            "Wealth": 3,
            "Grain": "0",
            "Wood": 1,
            "Iron": 1,
            "Stone": 5,
        },
        "Icons": [
            { "ID": "Tile owned", "Text": "D", "Optional": "Domas" },
            { "ID": "Tile owned", "Text": "D", "Optional": "Domas" },
            { "ID": "Tile owned", "Text": "D", "Optional": "Domas" },
            { "ID": "Arrow" },
            { "ID": "Place tile", "Text": "F", "Optional": "Industry" },
        ],
        "Text": "To play this card, you must own 3 Domas.\rBuild a Farm",
        "After": "Once",
    },
    {
        "Name": "Silvanus family",
        "Type": "Family",
        "Family type": "Standard",
        "Image": "Family",
        "Starting resources": {
            "Power": 3,
            "Wealth": 3,
            "Grain": 1,
            "Wood": "0",
            "Iron": 5,
            "Stone": 1,
        },
        "Icons": [
            { "ID": "Tile owned", "Text": "S", "Optional": "Shop" },
            { "ID": "Tile owned", "Text": "S", "Optional": "Shop" },
            { "ID": "Tile owned", "Text": "S", "Optional": "Shop" },
            { "ID": "Arrow" },
            { "ID": "Place tile", "Text": "L", "Optional": "Industry" },
        ],
        "Text": "To play this card, you must own 3 Shops.\rBuild a Lumber mill",
        "After": "Once",
    },
]