cardInfo = [
    {
        "Name": "The Powerful",
        "Type": "Beginner",
        "Influence": "8",
        "Aureus": "6",
        "Grain": "3",
        "Wood": "3",
        "Metal": "2",
        "Papyrus": "2",
        "Draw cards": "3",
    },
    {
        "Name": "The Wealthy",
        "Type": "Beginner",
        "Influence": "7",
        "Aureus": "9",
        "Grain": "2",
        "Wood": "2",
        "Metal": "2",
        "Papyrus": "2",
        "Draw cards": "3",
    },
    {
        "Name": "The Powerful",
        "Type": "Beginner",
        "Influence": "8",
        "Aureus": "6",
        "Grain": "3",
        "Wood": "3",
        "Metal": "2",
        "Papyrus": "2",
        "Draw cards": "3",
    },
    {
        "Name": "The Wealthy",
        "Type": "Beginner",
        "Influence": "7",
        "Aureus": "9",
        "Grain": "2",
        "Wood": "2",
        "Metal": "2",
        "Papyrus": "2",
        "Draw cards": "3",
    },
    {
        "Name": "The Powerful",
        "Type": "Beginner",
        "Influence": "8",
        "Aureus": "6",
        "Grain": "3",
        "Wood": "3",
        "Metal": "2",
        "Papyrus": "2",
        "Draw cards": "3",
    },
    {
        "Name": "The Wealthy",
        "Type": "Beginner",
        "Influence": "7",
        "Aureus": "9",
        "Grain": "2",
        "Wood": "2",
        "Metal": "2",
        "Papyrus": "2",
        "Draw cards": "3",
    },
];