cardInfo = [
    {
        "Name": "The Powerful",
        "Type": "Beginner",
        "Influence": "4",
        "Aureus": "3",
        "Grain": "2",
        "Wood": "2",
        "Metal": "1",
        "Papyrus": "1",
        "Draw cards": "3",
    },
    {
        "Name": "The Wealthy",
        "Type": "Beginner",
        "Influence": "3",
        "Aureus": "4",
        "Grain": "1",
        "Wood": "1",
        "Metal": "1",
        "Papyrus": "1",
        "Draw cards": "3",
    },
    {
        "Name": "The Powerful",
        "Type": "Beginner",
        "Influence": "4",
        "Aureus": "3",
        "Grain": "2",
        "Wood": "2",
        "Metal": "1",
        "Papyrus": "1",
        "Draw cards": "3",
    },
    {
        "Name": "The Wealthy",
        "Type": "Beginner",
        "Influence": "3",
        "Aureus": "4",
        "Grain": "1",
        "Wood": "1",
        "Metal": "1",
        "Papyrus": "1",
        "Draw cards": "3",
    },
];