var tileSummary = [
    {
        "Name": "Domas",
        "Background": "Home",
        "Resource": "Grain",
        "Costs": [
            -3,
            -3,
            -3,
            -3,
            -3,
            -4,
            -4,
            -4,
            -4,
            -4,
            -5,
            -5,
            -5,
            -5,
            -5,
            -6,
            -6,
            -6,
            -6,
            -7,
            -7,
            -7,
            -8,
            -9,
        ],
    },
    {
        "Name": "Shop",
        "Background": "Shop",
        "Resource": "Wood",
        "Costs": [
            -3,
            -4,
            -4,
            -5,
            -5,
            -5,
            -6,
            -6,
            -6,
            -6,
            -7,
            -7,
            -7,
            -8,
            -8,
            -8,
            -9,
            -9,
            -9,
            -10,
            -10,
        ],
    },
    {
        "Name": "Temple",
        "Background": "Temple",
        "Resource": "Metal",
        "Costs": [
            -4,
            -5,
            -5,
            -6,
            -6,
            -7,
            -7,
            -7,
            -8,
            -8,
            -9,
            -9,
            -10,
            -11,
            -12,
            -14,
            -16,
        ],
        "Type": "Religion",
    },
    {
        "Name": "Library",
        "Background": "Civic",
        "Resource": "Papyrus",
        "Costs": [
            -4,
            -5,
            -5,
            -6,
            -6,
            -7,
            -7,
            -7,
            -8,
            -8,
            -8,
            -9,
            -10,
            -11,
            -12,
            -14,
            -16,
            -18,
        ],
    },
    {
        "Name": "Amphitheatre",
        "Repeat": 3,
    },
    {
        "Name": "Oracle",
        "Type": "Religion",
        "Background": "Temple",
        "Repeat": 3,
    },
    {
        "Name": "Barracks",
        "Type": "Military",
        "Background": "Military",
        "Repeat": 6,
    },
    {
        "Name": "Parade",
        "Type": "Military",
        "Background": "Military",
        "Repeat": 4,
    },
]

var tileInfo = [];
for (var i = 0; i < tileSummary.length; i++) {
    if (tileSummary[i]["Costs"]) {
        for (var j = 0; j < tileSummary[i]["Costs"].length; j++) {
            tileInfo.push({
                "Name": tileSummary[i]["Name"],
                "Type": tileSummary[i]["Type"],
                "Background": tileSummary[i]["Background"],
                "Resource": tileSummary[i]["Resource"],
                "Cost": tileSummary[i]["Costs"][j],
            });
        }
    } else {
        for (var j = 0; j < tileSummary[i]["Repeat"]; j++) {
            tileInfo.push({
                "Name": tileSummary[i]["Name"],
                "Type": tileSummary[i]["Type"],
                "Background": tileSummary[i]["Background"],
            });
        }
    }
}